### ISSUE TITLE
2017-11: daily report

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#11]
## 2017-11-03:
- Have done:
  -  [cine.web 工程迁移到GIT，部署脚本兼容GIT] @daweilv 
  -  iOS-项目架构:   提供 Cine.iOS 工程项目的创建文档Doc [( #111 )](https://github.com/bstcine/cine-tasklist/issues/111) @Zohar
  -  iOS-项目架构：提供 Carthage 替换 Cocoapods 的方案，并编写文档 [( #112 )](https://github.com/bstcine/cine-tasklist/issues/112) @Zohar
  -  API-iOS: iOS发布版本前，积分计算规则-先避免输入超过可用积分变为0的情况 [( #102 )](https://github.com/bstcine/cine-tasklist/issues/102) @leo
  -  PC-后台-课程管理：课件批量录入 [( #21 )](https://github.com/bstcine/cine-tasklist/issues/21) @leo
  -  api-Code规范：提供V2版本的api [( #42 )](https://github.com/bstcine/cine-tasklist/issues/42)( 2.4个人中心 部分api) @leo
  -  Android-Code调整：移动端使用统一的Model定义，然后代码check in `Gitee` [( #94 )](https://github.com/bstcine/cine-tasklist/issues/90) @kim

- Working:
  - [ ] pc-H5: 词汇量测试设计 [( #86 )](https://github.com/bstcine/cine-tasklist/issues/86) @David
  - [ ] pc-后台管理: 词汇量测试设计 - 文档数据导入 [( #115 )](https://github.com/bstcine/cine-tasklist/issues/115) @leo
  - [ ] 安卓-下载：已下载课程目录显示方式 [( #49 )](https://github.com/bstcine/cine-tasklist/issues/49) @kim
  - [ ] iOS-Code规范：把现有的功能迁移到V2 [( #84 )](https://github.com/bstcine/cine-tasklist/issues/84) @Aaron 
  - [ ] iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 [( #60 )](https://github.com/bstcine/cine-tasklist/issues/60) @Zohar
  - [ ] PC-Tool: 压缩音频，图片。 及在图片上面加水印 [( #114 )](https://github.com/bstcine/cine-tasklist/issues/114) @kim

<br>
<br>

## 2017-11-10:
- Have done:
  - API: 双11活动 - 新用户满3500送pad&老用户1500送pad [( #99 )](https://github.com/bstcine/cine-tasklist/issues/99) @daweilv 
  - PC-Pad：产品结算中心页收货地址定制，添加颜色备注 [( #124 )](https://github.com/bstcine/cine-tasklist/issues/124) @daweilv 
  - PC：暨阳中学登录页面跳转更改 [( #116 )](https://github.com/bstcine/cine-tasklist/issues/116) @daweilv 
  - PC: 微信分享开通&&金额<=1.00的课程, 不再发邮件提醒公司内部人员 [( #106 )](https://github.com/bstcine/cine-tasklist/issues/106) @daweilv 
  - PC-后台-商城-订单管理：手动开通课程课程权限页面新增实付总金额功能 [( #91 )](https://github.com/bstcine/cine-tasklist/issues/91) @daweilv 
  - [现网node环境升级，代码升级部署] @daweilv 
  - PC: 双11活动一元购-某些课程分享拿优惠券[( #98 )](https://github.com/bstcine/cine-tasklist/issues/98) @daweilv 
  - PC: 确认订单页的如有收货地址，增加必填校验 [( #141 )](https://github.com/bstcine/cine-tasklist/issues/141) @daweilv 
  - api-Code规范：提供V2版本的api [( #42 )](https://github.com/bstcine/cine-tasklist/issues/42)（2.5 分享 部分api） @Leo
  - api-Code规范：提供V2版本的api [( #42 )](https://github.com/bstcine/cine-tasklist/issues/42)
（2.3 权限 部分api，修改我的学习列表排序和首页课程排序保持一致） @Leo
  - 去掉- 低价产品(1000元以下含1000)优惠券最高抵扣100元限制 [( #133 )](https://github.com/bstcine/cine-tasklist/issues/133) @Leo
  - PC-后台-课程管理：课件批量录入 [( #21 )](https://github.com/bstcine/cine-tasklist/issues/21)
（修改命名规则，支持一个文件拆分多个的情况） @Leo
  - iOS：无网络情况下出现的bug [( #130 )](https://github.com/bstcine/cine-tasklist/issues/130) Zohar
  - iOS-学习系统：未登录状态下，在学习页面也显示了已购买的课程列表 [( #129 )](https://github.com/bstcine/cine-tasklist/issues/129) Zohar
  - iOS - 项目架构 使用 Realm 技术搭建数据库探索 [( #113 )](https://github.com/bstcine/cine-tasklist/issues/113) Zohar
  - iOS-下载：下载多个lesson时，有些lesson一直处于读取状态，无法开始下载 [( #83 )](https://github.com/bstcine/cine-tasklist/issues/83) @Zohar
   -  安卓-下载：已下载课程目录显示方式[( #49 )](https://github.com/bstcine/cine-tasklist/issues/49) @Kim
   - PC-Tool: 压缩音频、压缩图片、及图片加水印[( #114 )](https://github.com/bstcine/cine-tasklist/issues/114) @Kim
   - 安卓-下载：隐藏当前用户未购买的缓存课程[( #132 )](https://github.com/bstcine/cine-tasklist/issues/132) @Kim
   - 安卓-个人设置：我的积分页面显示连接出错[( #92 )](https://github.com/bstcine/cine-tasklist/issues/92) @Kim
  - iOS-Code规范：迁移到项目的V2框架 - Util 模块[( #66 )](https://github.com/bstcine/cine-tasklist/issues/66) @Aaron

    
- Working:
  - [ ] pc-H5: 词汇量测试设计 [( #86 )](https://github.com/bstcine/cine-tasklist/issues/86) @daweilv 
  - [ ] pc-后台管理: 词汇量测试设计 - 文档数据导入 [( #115 )](https://github.com/bstcine/cine-tasklist/issues/115) @Leo
  - [ ] iOS-Code规范：把现有的功能迁移到V2 [( #84 )](https://github.com/bstcine/cine-tasklist/issues/84) @Aaron
  - [ ] iOS-下载：课程内容的本地自动更新下载 - V2的代码结构设计 [( #120 )](https://github.com/bstcine/cine-tasklist/issues/120) @Zohar
  - [ ] iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 [( #60 )](https://github.com/bstcine/cine-tasklist/issues/60) @Zohar

<br>
<br>

### Have done:
- [ ]   PC-H5: 词汇量测试设计  [(#86)](https://github.com/bstcine/cine-tasklist/issues/86) @daweilv  `Working`
- [x]   PC-后台管理: 词汇量测试设计 - 文档数据导入 [(#115)](https://github.com/bstcine/cine-tasklist/issues/115) @iott
- [x]   PC-邮件提醒: 销售报表每日邮件推送  [(#123)](https://github.com/bstcine/cine-tasklist/issues/123) @iott
- [x]  Android-个人设置: 开通了该课程权限的用户，才能在“我的下载”中访问该课程 [(#144)](https://github.com/bstcine/cine-tasklist/issues/144) @Kim
- [ ]  PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等 [(#137)](https://github.com/bstcine/cine-tasklist/issues/137) @Kim
- [x]  iOS-Code规范：把现有的功能迁移到V2 [(#84)](https://github.com/bstcine/cine-tasklist/issues/84) @Arron
 - [双11活动买课送书的清单导出] @David
 - [数据库无用表整理] @David
  - iOS-学习系统：播放界面课程标题 [(#34)](https://github.com/bstcine/cine-tasklist/issues/34) @Leo
  - 安卓-购买与支付：课程详情页里面的图片需要不加www.bstcine.com前缀也能正常显示[(#117)](https://github.com/bstcine/cine-tasklist/issues/117) @Kim
  - Android-Code调整：移动端使用统一的Model定义，然后代码check in `Gitee`[(#90)](https://github.com/bstcine/cine-tasklist/issues/90) @Kim
   - PC-后台管理:数据维护误操作可能存在情况[(#137)](https://github.com/bstcine/cine-tasklist/issues/107) @Kim
<br>

### Working:
- [x]   pc-H5: 词汇量测试设计 [(#86)](https://github.com/bstcine/cine-tasklist/issues/86) @daweilv 

<br>
<br>

### Have done:
- [x]   PC-H5: 词汇量测试设计  [(#86)](https://github.com/bstcine/cine-tasklist/issues/86) @daweilv  `Working`
- [x] Android: V1.1.7版本发布   (......,  [#49](../../cine-tasklist/issues/49) , [#93](../../cine-tasklist/issues/93) , [#197](../../cine-tasklist/issues/97) , [#156](../../cine-tasklist/issues/156) , #142)   @Kim
- [x] iOS-V2: 未完成的功能列表   [(#158)](../../cine-tasklist/issues/158)    @AaronLiDangkun 
- [x]  API-购买与支付:  学习机专门优惠券  [(#155)](../../cine-tasklist/issues/155) @iott 
- [x]  API-购买与支付: 订单预先准备中包含匹配的优惠券及积分 [(#157)](../../cine-tasklist/issues/157) @iott 
- [ ]  PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等[(#137)](../../cine-tasklist/issues/137) @Kim
- Android-个人设置: 地区、年龄、更新年级均为下拉框形式   [(#156)](../../cine-tasklist/issues/156) @Kim
- 安卓-下载：当账号被登录后，第一次点击播放已下载的课程只有声音，没有图片 [(#97)](../../cine-tasklist/issues/97)@Kim
- 优化缓存模块、优化 Pad 二维码分享、1.1.7版本发布 @Kim
- PC-后台-商城：购买课程时使用的积分数可为小数 [(#80)](https://github.com/bstcine/cine-tasklist/issues/80)  @Leo
- iOS-Code规范：把现有的功能迁移到V2 [(#84)](https://github.com/bstcine/cine-tasklist/issues/84) @Aaron
<br>

### Working:
- [ ]   数据统计: 学习过程、课程详情页、购买&分享统计 [(#127)](https://github.com/bstcine/cine-tasklist/issues/127)
 - [ ]   iOS-V2版本：测试问题反馈列表 ([#148](https://github.com/bstcine/cine-tasklist/issues/148)) @Aaron
<br>
<br>

## 2017-12-01:
- Have done:
- [x]  API: 课程详情页， 没有登录的用户也可以点击分享 [(#136)](../../cine-tasklist/issues/136)
- [x]  api-订单支付状态：客户同一门课程支付两次，两次都支付成功 [(#53)](../../cine-tasklist/issues/53)
- [x]  iOS-V2：测试问题反馈-必须解决列表   [(#174)](../../cine-tasklist/issues/174)
- [x]  Android-H5: 词汇量测试设计  [(#169)](../../cine-tasklist/issues/169) @Kim
- [x]  Android-学习系统: Lesson播放界面改为和苹果App一样的播放模式   [(#167)](../../cine-tasklist/issues/167) @Kim
- [x]  PC-安全: 走马灯功能-在视频播放过程中，随机出现用户信息    [(#172)](../../cine-tasklist/issues/172) @daweilv 
       - 代码优化  @Kim
       - Android-Pad-分享：在目前提供的Pad学习机上，App无法分享出去 [(#183)](https://github.com/bstcine/cine-tasklist/issues/183) @Kim
- [ ]  pc-H5: 新版的 精读课程详情&&音频课程详情&&书籍课程详情    [(#36)](../../cine-tasklist/issues/36)
```
App 版的 Demo
```
- [x]  其它  @Leo
```
1.apptest media上传路径修改为www目录下
2.添加media host配置
3.历史超时订单处理
4.48小时超时订单自动关闭[创建第三方订单添加失效时间，关闭第三方订单，订单列表检查检查]
5.添加api返回token，ios审核使用
6.apptest 数据库同步
``` 

<br>

- Working:
- [ ]   PC: 部分用户高考全国卷课程无法学习 ([#121](../../cine-tasklist/issues/121))
- [ ] cine.pwa 前端构建工程持续完善  [(#186)](https://github.com/bstcine/cine-tasklist/issues/186) @David
- [ ] pc-H5: 词汇量测试设计  [(#86)](https://github.com/bstcine/cine-tasklist/issues/86) @David
```
 原始需求已完成，新增修改需求working
```
- [ ]  Database：表名规范 [(#179)](https://github.com/bstcine/cine-tasklist/issues/179) @Leo 
- [ ] iOS-V2：测试问题反馈-必须解决列表 ([#174](https://github.com/bstcine/cine-tasklist/issues/174)) @Aaron
- [ ] iOS-V2：未完成的功能列表  ([#158](https://github.com/bstcine/cine-tasklist/issues/158)) @Aaron
- [ ] iOS-V2版本：测试问题反馈列表 ([#148](https://github.com/bstcine/cine-tasklist/issues/148)) @Aaron

**Comment by MaryLinker** [comment]
- Android-个人设置: 地区、年龄、更新年级均为下拉框形式（[#156]） (https://github.com/bstcine/cine-tasklist/issues/156) @Kim
   - 安卓-下载：当账号被登录后，第一次点击播放已下载的课程只有声音，没有图片（[#97]） (https://github.com/bstcine/cine-tasklist/issues/97) @Kim
   - 优化缓存模块、优化 Pad 二维码分享、1.1.7版本发布 @Kim
   - PC-后台-商城：购买课程时使用的积分数可为小数（[#80]） (https://github.com/bstcine/cine-tasklist/issues/80) @Leo
- iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84)) @Aaron
- iOS-V2：未完成的功能列表  ([#158](https://github.com/bstcine/cine-tasklist/issues/158)) @Aaron

- iOS-V2版本：测试问题反馈列表 ([#148](https://github.com/bstcine/cine-tasklist/issues/148)) @Aaron
