### ISSUE TITLE
2017-11: daily report - Zohar

### ISSUE THREAD

**Issue by YinZhenJob** [bstcine/cine-dailyreport#12]
11月3日：
- Have done:
1. [iOS-项目架构 提供 Cine.iOS 工程项目的创建文档Doc #111](https://github.com/bstcine/cine-tasklist/issues/111)
2. [iOS-项目架构：提供 Carthage 替换 Cocoapods 的方案，并编写文档 #112](https://github.com/bstcine/cine-tasklist/issues/112)
3. [iOS - 项目架构 使用 Realm 技术搭建数据库探索 #113](https://github.com/bstcine/cine-tasklist/issues/113)

- Working:
-  [ ]  [iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60](https://github.com/bstcine/cine-tasklist/issues/60)

11月7日：
- Have done:

- Working:
- [ ]  [iOS-下载：课程内容的本地自动更新下载 - V2的代码结构设计 #120](https://github.com/bstcine/cine-tasklist/issues/120)
- [ ]  [iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60](https://github.com/bstcine/cine-tasklist/issues/60)

11月10日：
- Have done:
-  [iOS：无网络情况下出现的bug #130](https://github.com/bstcine/cine-tasklist/issues/130)
-  [iOS-学习系统：未登录状态下，在学习页面也显示了已购买的课程列表 #129](https://github.com/bstcine/cine-tasklist/issues/129)
-  [iOS - 项目架构 使用 Realm 技术搭建数据库探索 #113](https://github.com/bstcine/cine-tasklist/issues/113)
- [iOS-下载：下载多个lesson时，有些lesson一直处于读取状态，无法开始下载 #83](https://github.com/bstcine/cine-tasklist/issues/83)

- Working:
- [ ]  [iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60](https://github.com/bstcine/cine-tasklist/issues/60)

11月14日：
11月17日：
11月21日：
11月24日：
11月28日：
