### ISSUE TITLE
2017-11: daily report - Aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#13]
2017-11-03

Have done:

Working:
- [ ] iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84))

2017-11-07

Have done:

Working:

2017-11-10

Have done:

Working:

- [ ] [#66 iOS-Code规范：迁移到项目的V2框架 - Util 模块](https://github.com/bstcine/cine-tasklist/issues/66)
- [ ] iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84))

2017-11-14

Have done:

Working:
- [ ] iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84))

2017-11-17

Have done:

Working:
- [ ] iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84))

2017-11-21

Working:
- [ ] iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84))

2017-11-24

Working:

- [x] iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84))

2017-11-28

Working:

- [x] iOS-购买与支付：结算中心, `备注`栏里增加颜色的提示信息(设备类型课程) ([#161](https://github.com/bstcine/cine-tasklist/issues/161))
- [ ] iOS-V2：测试问题反馈-必须解决列表 ([#174](https://github.com/bstcine/cine-tasklist/issues/174))

**Comment by AaronLiDangkun** [comment]
2017-11-03

Have done:

Working:


2017-11-07

Have done:

Working:


2017-11-10

Have done:

Working:


2017-11-14

Have done:

Working:


2017-11-17

Have done:

Working:
