### ISSUE TITLE
2017-11: daily report - Leo

### ISSUE THREAD

**Issue by iott** [bstcine/cine-dailyreport#14]
### 2017-11-3
- Have done:
- [x]   [API-iOS: iOS发布版本前，积分计算规则-先避免输入超过可用积分变为0的情况 #102](https://github.com/bstcine/cine-tasklist/issues/102)
- [x]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
   2.4个人中心 部分api
 ```
- Working:
    [pc-后台管理: 词汇量测试设计 - 文档数据导入 #115](https://github.com/bstcine/cine-tasklist/issues/115)

<br>

### 2017-11-7
- Have done:
- [x]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
   2.5 分享 部分api
 ```
- Working:
- [x]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
   2.3 权限 部分api
 ```
<br>

### 2017-11-10
 - Have done:
 - [x]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
    2.3 权限 部分api
    修改我的学习列表排序和首页课程排序保持一致
 ```
 - [x] [去掉- 低价产品(1000元以下含1000)优惠券最高抵扣100元限制 #133](https://github.com/bstcine/cine-tasklist/issues/133)
 - [x] [PC-后台-课程管理：课件批量录入 #21](https://github.com/bstcine/cine-tasklist/issues/21)
```
修改命名规则，支持一个文件拆分多个的情况
```
- Working:
- [ ]  [pc-后台管理: 词汇量测试设计 - 文档数据导入 #115](https://github.com/bstcine/cine-tasklist/issues/115)
<br>

### 2017-11-14
 - Have done:
 - [x] [iOS-学习系统：播放界面课程标题 #34](https://github.com/bstcine/cine-tasklist/issues/34)
- Working:
- [x]  [pc-后台管理: 词汇量测试设计 - 文档数据导入 #115](https://github.com/bstcine/cine-tasklist/issues/115)
<br>

### 2017-11-17
 - Have done:
- [x]  [pc-后台管理: 词汇量测试设计 - 文档数据导入 #115](https://github.com/bstcine/cine-tasklist/issues/115)
- [x]  [PC-邮件提醒: 销售报表每日邮件推送 #123](https://github.com/bstcine/cine-tasklist/issues/123)
<br>

### 2017-11-21
 - Have done:
- [x]  [PC-后台-商城：购买课程时使用的积分数可为小数 #80](https://github.com/bstcine/cine-tasklist/issues/80)

- Working:
 - [ ] [API-购买与支付: 学习机专门优惠券 #155](https://github.com/bstcine/cine-tasklist/issues/155)
 - [ ] [API-购买与支付: 订单预先准备中包含匹配的优惠券及积分 #157](https://github.com/bstcine/cine-tasklist/issues/157)

<br>

### 2017-11-24
 - Have done:
- [x]  [API-购买与支付: 订单预先准备中包含匹配的优惠券及积分 #157](https://github.com/bstcine/cine-tasklist/issues/157)
- [x]  [API-购买与支付: 学习机专门优惠券 #155](https://github.com/bstcine/cine-tasklist/issues/155)

<br>

<br>

### 2017-11-28
 - Have done:
- [x]  [API: 课程详情页， 没有登录的用户也可以点击分享 #136](https://github.com/bstcine/cine-tasklist/issues/136)
