### ISSUE TITLE
2017-11: daily report - David

### ISSUE THREAD

**Issue by daweilv** [bstcine/cine-dailyreport#15]
- 2017-11-03
  - Have done:
  [工程迁移到GIT，部署脚本兼容GIT]
  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)

<br>

- 2017-11-07
  - Have done:
   [API: 双11活动 - 新用户满3500送pad&老用户1500送pad #99](https://github.com/bstcine/cine-tasklist/issues/99)
   [PC-Pad：产品结算中心页收货地址定制，添加颜色备注 #124](https://github.com/bstcine/cine-tasklist/issues/124)
   [PC：暨阳中学登录页面跳转更改 #116](https://github.com/bstcine/cine-tasklist/issues/116)
   [PC: 微信分享开通&&金额<=1.00的课程, 不再发邮件提醒公司内部人员 #106](https://github.com/bstcine/cine-tasklist/issues/106)
   [PC-后台-商城-订单管理：手动开通课程课程权限页面新增实付总金额功能 #91](https://github.com/bstcine/cine-tasklist/issues/91)

  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)

<br>

- 2017-11-10
  - Have done:
  [现网node环境升级，代码升级部署]
  [分享购修改](https://github.com/bstcine/cine-tasklist/issues/98)
  [PC: 确认订单页的如有收货地址，增加必填校验 #141](https://github.com/bstcine/cine-tasklist/issues/141)
  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)

<br>

- 2017-11-14
  - Have done:
  [双11活动买课送书的清单导出]
  [数据库无用表整理]
  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)
  > 后端接口已完成 99%，等待 UI 定稿

<br>

- 2017-11-17
  - Have done:
   [双11活动买课送书的清单导出]
   [数据库无用表整理]
  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)
  > 后端接口已完成 99% 

<br>

- 2017-11-21
  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)
  > 前端80%

<br>

 - 2017-11-24
  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)

<br>

- 2017-11-28
  - Working:
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)

<br>

- 2017-12-01
  - Have done:
  - [x] [PC-安全: 走马灯功能-在视频播放过程中，随机出现用户信息](https://github.com/bstcine/cine-tasklist/issues/172)
  - Working:
  - [ ] [cine.pwa 前端构建工程持续完善](https://github.com/bstcine/cine-tasklist/issues/186)
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86)
  > 原始需求已完成，新增修改需求working
  - [ ] [pc-H5: 新版的 精读课程详情&&音频课程详情&&书籍课程详情 #36](https://github.com/bstcine/cine-tasklist/issues/36)

<br>
