### ISSUE TITLE
2017-11: daily report - Kim

### ISSUE THREAD

**Issue by kimliss** [bstcine/cine-dailyreport#16]
### 2017-11-07
- Have done:
   - [x]  [#49 安卓-下载：已下载课程目录显示方式](https://github.com/bstcine/cine-tasklist/issues/49)

- Working:
   - [ ]  [#114 PC-Tool: 压缩音频、压缩图片、及图片加水印](https://github.com/bstcine/cine-tasklist/issues/114)
   - [ ]  [#132 安卓-下载：隐藏当前用户未购买的缓存课程](https://github.com/bstcine/cine-tasklist/issues/132)
   - [ ] [#92 安卓-个人设置：我的积分页面显示连接出错](https://github.com/bstcine/cine-tasklist/issues/92)

### 2017-11-10
- Have done:
   - [ ]  [#114 PC-Tool: 压缩音频、压缩图片、及图片加水印](https://github.com/bstcine/cine-tasklist/issues/114)
   - [ ]  [#132 安卓-下载：隐藏当前用户未购买的缓存课程](https://github.com/bstcine/cine-tasklist/issues/132)
   - [ ] [#92 安卓-个人设置：我的积分页面显示连接出错](https://github.com/bstcine/cine-tasklist/issues/92)
- Working:
   - [ ]  [#117 安卓-购买与支付：课程详情页里面的图片需要不加 http://www.bstcine.com前缀也能正常显示](https://github.com/bstcine/cine-tasklist/issues/117)
   - [ ]  [#90 Android-Code调整：移动端使用统一的Model定义，然后代码check in `Gitee`](https://github.com/bstcine/cine-tasklist/issues/90)

### 2017-11-14
- Have done:
   - [ ]  [#117 安卓-购买与支付：课程详情页里面的图片需要不加 http://www.bstcine.com前缀也能正常显示](https://github.com/bstcine/cine-tasklist/issues/117)
   - [ ]  [#90 Android-Code调整：移动端使用统一的Model定义，然后代码check in `Gitee`](https://github.com/bstcine/cine-tasklist/issues/90)
- Working:
   - [ ]  [#137 PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等](https://github.com/bstcine/cine-tasklist/issues/137)

### 2017-11-17
- Have done:
   - [ ]  [#137 PC-后台管理:数据维护误操作可能存在情况](https://github.com/bstcine/cine-tasklist/issues/107)
- Working:
   - [ ]  [#137 PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等](https://github.com/bstcine/cine-tasklist/issues/137)

### 2017-11-21
- Have done:
   - [ ]  [#156 Android-个人设置: 地区、年龄、更新年级均为下拉框形式](https://github.com/bstcine/cine-tasklist/issues/156)
   - [ ]  [#97 安卓-下载：当账号被登录后，第一次点击播放已下载的课程只有声音，没有图片](https://github.com/bstcine/cine-tasklist/issues/97)
- Working:
   - [ ]  [#137 PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等](https://github.com/bstcine/cine-tasklist/issues/137)

### 2017-11-24
- Have done:
   - 优化缓存模块、优化 Pad 二维码分享、1.1.7版本发布
- Working:
   - [ ]  [#137 PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等](https://github.com/bstcine/cine-tasklist/issues/137)

### 2017-11-28
- Have done:
   - 代码优化 
- Working:
   - [ ]  [#183 Android-Pad-分享：在目前提供的Pad学习机上，App无法分享出去](https://github.com/bstcine/cine-tasklist/issues/183)
   - [ ]  [#167 Android-学习系统: Lesson播放界面改为和苹果App一样的播放模式](https://github.com/bstcine/cine-tasklist/issues/167)
   - [ ]  [#169 Android-H5: 词汇量测试设计](https://github.com/bstcine/cine-tasklist/issues/169)

### 2017-12-01
- Have done:
   - [ ]  [#183 Android-Pad-分享：在目前提供的Pad学习机上，App无法分享出去](https://github.com/bstcine/cine-tasklist/issues/183)
   - [ ]  [#167 Android-学习系统: Lesson播放界面改为和苹果App一样的播放模式](https://github.com/bstcine/cine-tasklist/issues/167)
   - [ ]  [#169 Android-H5: 词汇量测试设计](https://github.com/bstcine/cine-tasklist/issues/169)
- Working:

**Comment by kimliss** [comment]
### 2017-11-xx
- Have done:
 [#xxx xxx](https://github.com/bstcine/cine-tasklist/issues/xxx)
- Working:
- [ ]  [#xxx xxx](https://github.com/bstcine/cine-tasklist/issues/xxx)
