### ISSUE TITLE
2017-12: daily report

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#17]
## 2017-12-08:
- Have done:
- [x] iOS-V2：测试问题反馈-必须解决列表 ([#174](../../cine-tasklist/issues/174)) @Aaron
- [x] iOS-更新: 规范app需要更新时弹出的UI  ([#192](../../cine-tasklist/issues/192)) 
- [x] iOS-安全: 走马灯功能-在视频播放过程中，随机出现用户信息 ([#190](../../cine-tasklist/issues/190)) 
- [x] iOS-V2：V2.0.1 版本发布 - `2017-12-07`
- [x]  Android-安全: 走马灯功能-在视频播放过程中，随机出现用户信息 ([#194](../../cine-tasklist/issues/194)) 
- [x] 安卓-学习系统：课程播放界面的缓冲图更改 ([#93](../../cine-tasklist/issues/93)) 
- [x] 安卓-pad：V1.1.8 版本发布 -  `2017-12-07`
- [x]  Database：表名规范 [(#179)](../../cine-tasklist/issues/179) @Leo 
- [ ]  PC-后台：新建课程的页面中添加课程属性一栏，包括阶段、类别和推荐  [(#187)](../../cine-tasklist/issues/187)  @Leo
- [x]  pc-H5: cine.pwa 前端构建工程持续完善  [(#186)](../../cine-tasklist/issues/186) @David
- [x]  pc-H5: 词汇量测试设计  [(#86)](../../cine-tasklist/issues/86) @David
api-Code规范: 整理目录结构 [(#196)](https://github.com/bstcine/cine-tasklist/issues/196) @Leo 
Android-Pad-分享：在目前提供的Pad学习机上，App无法分享出去 [(#183)](https://github.com/bstcine/cine-tasklist/issues/183)  @Kim
Android-学习系统: Lesson播放界面改为和苹果App一样的播放模式 [(#167)](https://github.com/bstcine/cine-tasklist/issues/167)  @Kim
Android-V1.1.8：测试问题反馈列表  [(#197)](https://github.com/bstcine/cine-tasklist/issues/197) @Kim @Leo 
iOS-V2：未完成的功能列表  ([#158](https://github.com/bstcine/cine-tasklist/issues/158))  @aaron
iOS-注册与登录：取消邮箱注册入口 ([#199](https://github.com/bstcine/cine-tasklist/issues/199))  @aaron

<br>

- Working:
- [ ]  PC: 部分用户高考全国卷课程无法学习 ([#121](../../cine-tasklist/issues/121))   @Leo
- [ ]  Android-H5: 词汇量测试设计[(#169)](https://github.com/bstcine/cine-tasklist/issues/169) @Kim
- [ ]  PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等[(#137)](https://github.com/bstcine/cine-tasklist/issues/137) @Kim

<br>
<br>

## 2017-12-15:
- Have done:
- [x] iPhone-H5: 词汇量测试设计
- [x] 安卓-pad：V1.1.8 版本发布 `2017-12-11`
- [x] PC: 部分用户高考全国卷课程无法学习 ([#121](../../cine-tasklist/issues/121)) @Kim
```
清理 历史垃圾数据
```
- [x] Android-H5: 词汇量测试设计 ([#169](../../cine-tasklist/issues/169))
- [x] PC-Tool: 批量获取课程习题和单词 ([#195](../../cine-tasklist/issues/195)) @Kim
- [ ] PC-API: Lesson播放页-播放过程添加习题测试 ([#208](../../cine-tasklist/issues/208)) @Kim
- [ ] Android-学习系统: Lesson播放页-播放过程添加习题测试([#207](../../cine-tasklist/issues/207))
- [x] pc-H5: 词汇量测试-分享 ([#203](../../cine-tasklist/issues/203)) @daweilv  
- [x] H5-新版的课程详情页：精读&&音频&&书籍3种课程详情 ([#36](../../cine-tasklist/issues/36)) @daweilv 
```
提供了初步Demo
```

<br>

- Working:
- [ ] H5-个人设置: 地址信息管理 ([#206](../../cine-tasklist/issues/206)) @Kim
- [ ]  H5-新版的首页：添加课程筛选功能[(#152)](https://github.com/bstcine/cine-tasklist/issues/152)@daweilv
<br>
<br>

## 2017-12-22:
- Have done:
- [x] H5: cine.pwa 前端构建-项目结构规范  ([#215](../../cine-tasklist/issues/215)) @daweilv 
- [x] H5-新版的首页：添加课程筛选功能 ([#152](../../cine-tasklist/issues/152)) @daweilv 
```
初步Demo， 没有选择Tag功能
```
- [ ] API-购买与支付：购买前如果分享该课程，立刻享受95折 ([#160](../../cine-tasklist/issues/160)) @Leo
- [x] iPad-学习系统：学习广场&Lesson播放界面 ([#211](../../cine-tasklist/issues/211))  @Aaron
- [x] PC-后台管理: Lesson播放页-播放过程添加习题测试 ([#208](../../cine-tasklist/issues/208)) @Kim
- [x] API: Lesson播放页-播放过程添加习题测试 @Kim
 api-购买与支付：购买过《新概念英语第2册》课程的才可以购买纸质配套讲义[(#210)](https://github.com/bstcine/cine-tasklist/issues/210) @Leo

<br>

- Working:
- [ ] H5-学习系统: Lesson播放页-Media对应的习题测试 @Kim
- [ ]  Android-学习系统: Lesson播放页-播放过程添加习题测试[(#207)](https://github.com/bstcine/cine-tasklist/issues/207) @Kim
<br>
<br>

## 2017-12-29:
- Have done:
- [x] H5-新版的首页：添加课程筛选功能  ([#152](../../cine-tasklist/issues/152)) @daweilv 
```
Tag筛选待解决
```
- [x] H5-新版的课程详情页：精读&&音频&&书籍3种课程详情 ([#36](../../cine-tasklist/issues/36)) @daweilv 
```
Pad-横屏、竖屏
```
- [x] API-购买与支付：购买前如果分享该课程，立刻享受95折 ([#160](../../cine-tasklist/issues/160)) @Leo
- [x] Cine-WeChat：申请一个微信公众平台服务号 ([#213](../../cine-tasklist/issues/213)) @Leo
- [x] iPad-商城：首页&详情页&购买与支付 ([#219](../../cine-tasklist/issues/219))
- [ ] H5-学习系统: Lesson播放页-Media对应的习题测试  ([#225](../../cine-tasklist/issues/225)) @Kim
- [x] H5-个人设置: 地址信息管理 ([#206](../../cine-tasklist/issues/206)) @Kim
- [ ]  配置文档: Server Web Admin [后台配置](https://github.com/bstcine/help/wiki/Server-Web-Admin-%E5%90%8E%E5%8F%B0%E9%85%8D%E7%BD%AE)  @zhuyichun 
  PC-后台：H5-新版的首页需要添加课程属性Tag，包括阶段、类别[(#187)](https://github.com/bstcine/cine-tasklist/issues/187) @Leo
  pc-后台推送：注册用户群发邮件模板 [(#224)](https://github.com/bstcine/cine-tasklist/issues/224) @Leo
  H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情 [(#36)](https://github.com/bstcine/cine-tasklist/issues/36) @Leo
```
1.课程详情api调整
2.添加课程评价
```

<br>

- Working:
- [ ] H5-分享页：分享之后，新用户可领取优惠券(5%)，推荐人可获得积分奖励(10%)[(#105)](https://github.com/bstcine/cine-tasklist/issues/105) @Leo
```
1.分享领券后台逻辑
2.新用户买课推荐人送积分逻辑
```
- [ ] Android-学习系统: Lesson播放页-播放过程添加习题测试[(#207)](https://github.com/bstcine/cine-tasklist/issues/207) @Kim
<br>
<br>
