### ISSUE TITLE
2017-12: daily report - Aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#19]
## 2017-12-05

- Have done:
iOS-V2：测试问题反馈-必须解决列表 ([#174](https://github.com/bstcine/cine-tasklist/issues/174))
iOS-V2：未完成的功能列表  ([#158](https://github.com/bstcine/cine-tasklist/issues/158))

<br>

- Working:

<br>

## 2017-12-08

- Have done:
 iOS-更新: 规范app需要更新时弹出的UI  ([#192](https://github.com/bstcine/cine-tasklist/issues/192))
 iOS-安全: 走马灯功能-在视频播放过程中，随机出现用户信息 ([#190](https://github.com/bstcine/cine-tasklist/issues/190))

<br>

- Working:
- [x] iOS-注册与登录：取消邮箱注册入口 ([#199](https://github.com/bstcine/cine-tasklist/issues/199))

<br>

## 2017-12-12

- Have done:

<br>

- Working:
- [ ] iPad-学习系统：学习广场&Lesson播放界面 ([#211](https://github.com/bstcine/cine-tasklist/issues/211))

<br>

## 2017-12-15

- Have done:
iOS:

<br>

- Working:
- [ ] iOS-
- [ ] iPhone-H5: 词汇量测试 ([#204](https://github.com/bstcine/cine-tasklist/issues/204))

## 2017-12-19
- Have done:

<br>

- Working:
- [ ] iPad-学习系统：学习广场&Lesson播放界面 ([#211](https://github.com/bstcine/cine-tasklist/issues/211))

<br>

## 2017-12-22

- Have done:

<br>

- Working:
 - [x] iPad-学习系统：学习广场&Lesson播放界面 ([#211](https://github.com/bstcine/cine-tasklist/issues/211))

<br>

## 2017-12-26

- Have done:

<br>

- Working:
- [ ] iPad-商城：首页&详情页&购买与支付([ #219](https://github.com/bstcine/cine-tasklist/issues/219))

<br>

## 2017-12-29

- Have done:

<br>

- Working:
- [ ] iPad-商城：首页&详情页&购买与支付([ #219](https://github.com/bstcine/cine-tasklist/issues/219))
