### ISSUE TITLE
2017-12: daily report - Kim

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-dailyreport#20]
## 2017-12-05
- Have done:
     [#183 Android-Pad-分享：在目前提供的Pad学习机上，App无法分享出去](https://github.com/bstcine/cine-tasklist/issues/183)
    [#167 Android-学习系统: Lesson播放界面改为和苹果App一样的播放模式](https://github.com/bstcine/cine-tasklist/issues/167)
<br>

- Working:
- [ ]  [#169 Android-H5: 词汇量测试设计](https://github.com/bstcine/cine-tasklist/issues/169)
- [ ]  [#194 Android-安全: 走马灯功能-在视频播放过程中，随机出现用户信息](https://github.com/bstcine/cine-tasklist/issues/194)
- [ ]  [#137 PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等](https://github.com/bstcine/cine-tasklist/issues/137)
<br>

## 2017-12-08

- Have done:
    [#194 Android-安全: 走马灯功能-在视频播放过程中，随机出现用户信息](https://github.com/bstcine/cine-tasklist/issues/194)
    [#197 Android-V1.1.8：测试问题反馈列表](https://github.com/bstcine/cine-tasklist/issues/197)
<br>

- Working:
 - [ ]  [#137 PC-Tool: 压缩文件加水印, 校验数据, 计算Media的时间等](https://github.com/bstcine/cine-tasklist/issues/137)
<br>

## 2017-12-12

- Have done:
[#128 PC-API: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/208)

<br>

- Working:
 - [ ]  [#195 PC-Tool: 批量获取课程习题和单词](https://github.com/bstcine/cine-tasklist/issues/195)
<br>

## 2017-12-15

- Have done:
  [#195 PC-Tool: 批量获取课程习题和单词](https://github.com/bstcine/cine-tasklist/issues/195)
<br>

- Working:
 - [ ]  [#208 PC-后台管理: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/208) 部分完成
 - [ ]  [#207 Android-学习系统: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/207) 部分完成

## 2017-12-19
- Working:
 - [ ]  [#208 PC-后台管理: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/208) 部分完成
 - [ ]  [#207 Android-学习系统: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/207) 部分完成
<br>

## 2017-12-22

- Have done:
 [#208 PC-后台管理: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/208) 

<br>

- Working:
 - [ ]  [#207 Android-学习系统: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/207)

<br>

## 2017-12-26

- Have done:

<br>

- Working:
[#207 Android-学习系统: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/207)
[#206 H5-个人设置: 地址信息管理](https://github.com/bstcine/cine-tasklist/issues/206)

<br>

## 2017-12-29

- Have done:
[#206 H5-个人设置: 地址信息管理](https://github.com/bstcine/cine-tasklist/issues/206)

<br>

- Working:
[#207 Android-学习系统: Lesson播放页-播放过程添加习题测试](https://github.com/bstcine/cine-tasklist/issues/207)

**Comment by joelin109** [comment]
### 2017-12-xx
- Have done:
 [#xxx xxx](../../cine-tasklist/issues/xxx)
- Working:
- [ ]  [#xxx xxx](../../cine-tasklist/issues/xxx)

**Comment by MaryLinker** [comment]
api-购买与支付：购买过《新概念英语第2册》课程的才可以购买纸质配套讲义[(#210)](https://github.com/bstcine/cine-tasklist/issues/210)
