### ISSUE TITLE
2017-12: daily report - Leo

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-dailyreport#21]
## 2017-12-5
 - Have done:
 [Database：表名规范 #179](https://github.com/bstcine/cine-tasklist/issues/179)

<br>

- Working:
- [ ]  [PC: 部分用户高考全国卷课程无法学习 #121](https://github.com/bstcine/cine-tasklist/issues/121)

<br>

## 2017-12-8
 - Have done:
 [api-Code规范: 整理目录结构 #196](https://github.com/bstcine/cine-tasklist/issues/196)
 [Android-V1.1.8：测试问题反馈列表 #197](https://github.com/bstcine/cine-tasklist/issues/197)
```
1.2 & 1.4
```
- Working:

<br>

## 2017-12-12

- Have done:

<br>

- Working:

<br>

## 2017-12-15

- Have done:

<br>

- Working:
## 2017-12-19
- Have done:

<br>

- Working:

<br>

## 2017-12-22

- Have done:
[api-购买与支付：购买过《新概念英语第2册》课程的才可以购买纸质配套讲义 #210](https://github.com/bstcine/cine-tasklist/issues/210)

<br>

- Working:
 

<br>

## 2017-12-26

- Have done:
  API-购买与支付：购买前如果分享该课程，立刻享受95折 [(#160)](https://github.com/bstcine/cine-tasklist/issues/160)

<br>

- Working:
- [ ] Cine-WeChat：申请一个微信公众平台服务号 [(#213)](https://github.com/bstcine/cine-tasklist/issues/213)
- [ ] PC-后台：H5-新版的首页需要添加课程属性Tag，包括阶段、类别 [(#187)](https://github.com/bstcine/cine-tasklist/issues/187)

<br>

## 2017-12-29

- Have done:
Cine-WeChat：申请一个微信公众平台服务号 [(#213)](https://github.com/bstcine/cine-tasklist/issues/213)
PC-后台：H5-新版的首页需要添加课程属性Tag，包括阶段、类别 [(#187)](https://github.com/bstcine/cine-tasklist/issues/187)
 pc-后台推送：注册用户群发邮件模板 [(#224)](https://github.com/bstcine/cine-tasklist/issues/224)
H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情  [(#36)](https://github.com/bstcine/cine-tasklist/issues/36)
```
1.课程详情api调整
2.添加课程评价
```
<br>

- Working:
- [ ] H5-分享页：分享之后，新用户可领取优惠券(5%)，推荐人可获得积分奖励(10%) [(#105)](https://github.com/bstcine/cine-tasklist/issues/105)
```
1.分享领券后台逻辑
2.新用户买课推荐人送积分逻辑
```
