### ISSUE TITLE
2017-12: daily report - David

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-dailyreport#22]
## 2017-12-05
- Have done:

<br>

- Working:
 - [x] pc-H5: cine.pwa 前端构建工程持续完善 (#186) @david
 - [x] pc-H5: 词汇量测试设计 (#86) @david

<br>

## 2017-12-08

- Have done:

<br>

- Working:
 - [x] pc-H5: cine.pwa 前端构建工程持续完善 (#186) @david
 - [x] pc-H5: 词汇量测试设计 (#86) @david
 

<br>

## 2017-12-12

- Have done:
pc-H5: 词汇量测试-分享 ([#203](../../cine-tasklist/issues/203)) @daweilv  

<br>

- Working:
- [ ] H5-新版的课程详情页：精读&&音频&&书籍3种课程详情 ([#36](../../cine-tasklist/issues/36)) @daweilv 

<br>

## 2017-12-15

- Working:
- [ ] H5-新版的课程详情页：精读&&音频&&书籍3种课程详情 ([#36](../../cine-tasklist/issues/36)) @daweilv 
```
app 版基本 UI & 交互完成
```

 - [ ] H5-新版的首页：添加课程筛选功能([#152](../../cine-tasklist/issues/152))
```
pad 竖版基本 UI & 交互完成，横版 pad UI working
```

<br>

## 2017-12-19
- Have done:

<br>

- Working:
 - [ ] H5-新版的首页：添加课程筛选功能([#152](../../cine-tasklist/issues/152))

<br>

## 2017-12-22

- Have done:
- [x] H5: cine.pwa 前端构建-项目结构规范  ([#215](../../cine-tasklist/issues/215))

<br>

- Working:
 - [ ] H5-新版的首页：添加课程筛选功能([#152](../../cine-tasklist/issues/152))

<br>

## 2017-12-26

- Have done:

<br>

- Working:
 - [ ] H5-新版的首页：添加课程筛选功能([#152](../../cine-tasklist/issues/152))
```
功能完成，待提供基础数据测试
```

<br>

## 2017-12-29

- Have done:
 - [x] H5-新版的首页：添加课程筛选功能([#152](../../cine-tasklist/issues/152))

<br>

- Working:
- [ ] H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情  ([#36](../../cine-tasklist/issues/36))
