### ISSUE TITLE
2018-01: daily report

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#24]
## 2018-01-05:
- Have done:
- [x] H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情  ([#36](../../cine-tasklist/issues/36)) @David @leo
```
正式版
```
- [x] H5-分享页：分享之后，新用户可领取优惠券(5%)，推荐人可获得积分奖励(10%) ([#105](../../cine-tasklist/issues/105))   @David @leo
- [ ] Database-调整: 把lesson表medias字段数据存放在lesson_media表  ([#214](../../cine-tasklist/issues/214)) @Leo
- [ ] Android-个人设置: 地址信息管理 ([#206](../../cine-tasklist/issues/206))
- [x] H5-学习系统: Lesson播放页-Media对应的习题测试 ([#225](../../cine-tasklist/issues/225)) @Kim
- [ ] Android-学习系统: Lesson播放页-播放过程添加习题测试  ([#207](../../cine-tasklist/issues/207))
- [ ] H5-个人设置: 我的优惠券- 显示优惠券信息，与app类似  ([#122](../../cine-tasklist/issues/122)) @Kim
API-购买与支付：购买前如果分享该课程，立刻享受95折 ([#160](../../cine-tasklist/issues/160)) @Leo
```
 分享24小时内有效
 public和default的优惠：只针对视频课程类型
```

<br>

- Working:
- [ ]  PC-后台管理: Lesson播放页-播放过程添加习题测试 ([#208](../../cine-tasklist/issues/208)) @Kim
- [ ]  iPad-商城：首页&详情页&购买与支付([#219](../../cine-tasklist/issues/219)) @Aaron
- [ ] H5-商城：课程详情页 - 测试问题反馈列表 - V2.0.2 ([#222](../../cine-tasklist/issues/222))  @David @Leo

<br>
<br>

## 2018-01-12:
- Have done:
- [x] Database-调整: 把lesson表medias字段数据存放在lesson_media表  ([#214](../../cine-tasklist/issues/214)) @Leo
- [x] API-数据统计：数据来源(sitecode) 收集 - 订单、分享、登入  ([#229](../../cine-tasklist/issues/229))  @Leo
- [ ] H5-学习系统: Lesson播放页-Media对应的习题测试  ([#225](../../cine-tasklist/issues/225))  @Kim
- [x] PC-学习系统：账户需要强制进行手机号绑定 - H5  ([#228, #233](../../cine-tasklist/issues/233))  @Kim
- [x] Android-商城：新版的课程详情页-调用H5交互  ([#173](../../cine-tasklist/issues/173)) @Kim
- [ ] Android-学习系统: Lesson播放页-播放过程添加习题测试  ([#207](../../cine-tasklist/issues/207)) 
- [ ] H5-个人设置: 地址信息管理 ([#206](../../cine-tasklist/issues/206)) @Kim
- [x] iPad-商城：详情页&购买与支付 ([#219](../../cine-tasklist/issues/219))
- [x] iPad-商城：首页 ([#231](../../cine-tasklist/issues/231))
- [x] iPad-学习系统: Lesson播放页-Media对应的习题测试  ([#232](../../cine-tasklist/issues/232))
- [ ] iOS-购买与支付: 结算中心的收货地址信息管理 ([#241](../../cine-tasklist/issues/241))
- [x] iPhone-商城: 新版的课程详情页-调用H5交互  ([#95](../../cine-tasklist/issues/95))
- [x] H5-: 词汇量测试-测试记录&词汇量排位图 ([#218](../../cine-tasklist/issues/218))  @daweilv  
- [ ] H5-购买与支付：PC端的结算中心页面需要与APP端一致 ([#238](../../cine-tasklist/issues/238))

<br>

- Working:
- [ ] H5-商城：课程详情页 - 测试问题反馈列表  ([#222](../../cine-tasklist/issues/222))  @David 
- [ ] iPad-APP: 测试问题反馈列表- V2.0.2 ([#230](../../cine-tasklist/issues/230)) 

<br>
<br>

## 2018-01-19:
- Have done:
- [x] H5-个人设置: 地址信息管理   ([#206](../../cine-tasklist/issues/206))
- [x] iOS-购买与支付: 结算中心的收货地址信息管理    ([#241](../../cine-tasklist/issues/241))
- [x] API-购买与支付：订单需要包含收货地址等与发货信息  ([#242](../../cine-tasklist/issues/242))
- [ ] pc-H5: 词汇量测试-测试记录&词汇量排位图   ([#218](../../cine-tasklist/issues/218))
- [x] H5-购买与支付：PC端的结算中心页面需要与APP端一致  ([#238](../../cine-tasklist/issues/238))
- [x] H5-商城：课程详情页 - 测试问题反馈列表  ([#222](../../cine-tasklist/issues/222))  @David 
- [ ] iPad-APP: 测试问题反馈列表- V2.0.2 ([#230](../../cine-tasklist/issues/230)) 
- [ ] 商城-课程详情页：上线需要配置的课程概要\16:9图片\试听-V2.0.2 （#30） @Alice @Jerry

<br>

- Working:
- [ ] Android-APP: 测试问题反馈列表- V2.0.2 ([#244](../../cine-tasklist/issues/244)) 

<br>
<br>

## 2018-01-26:
- Have done:
- [x] pc-H5: 词汇量测试-测试记录&词汇量排位图   ([#218](../../cine-tasklist/issues/218))
```
待提供“学龄前”与“成人” 初始区间数据
```
- [x] 商城-课程详情页：上线需要配置的课程概要 -V2.0.2 （#30） @Alice @Jerry
```
还有17门待校验
```
- [x] H5-学习系统: Lesson播放页-Media对应的习题测试  ([#225](../../cine-tasklist/issues/225))  @Kim
- [x] H5-PC：测试问题反馈列表 - V2.0.2 ([#247](../../cine-tasklist/issues/247))
- [x] iPad-APP: 测试问题反馈列表- V2.0.2 ([#230](../../cine-tasklist/issues/230)) @Arron

<br>

- Working:
- [ ] iPhone-APP: 测试问题反馈列表- V2.0.2 ([#248](../../cine-tasklist/issues/248)) @Arron
- [ ] Android-APP: 测试问题反馈列表- V2.0.2  ([#244](../../cine-tasklist/issues/244)) @Kim @Mary

<br>
<br>

## 2018-02-02:
- Have done:
- [x] iPhone-APP: 测试问题反馈列表- V2.0.2 ([#248](../../cine-tasklist/issues/248)) @Arron
- [x] Android-APP: 测试问题反馈列表- V2.0.2  ([#244](../../cine-tasklist/issues/244)) @Kim 
- [ ] H5-商城：官网首页 - http://www.bstcine.com/ ([#256](../../cine-tasklist/issues/256))

<br>
<br>
