### ISSUE TITLE
2018-01: dailyreport - aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#25]
## 2018-01-05:
- Have done:

<br>

- Working:
- [ ] iPad-商城：首页&详情页&购买与支付([ #219](https://github.com/bstcine/cine-tasklist/issues/219))
- [ ] iOS-商城: 新版的课程详情页-调用H5交互 ([#95](https://github.com/bstcine/cine-tasklist/issues/95))

<br>
<br>

## 2018-01-08:
- Have done:

<br>

- Working:
- [ ] iPad-商城：首页&详情页&购买与支付([ #219](https://github.com/bstcine/cine-tasklist/issues/219))

<br>
<br>

## 2018-01-09:
- Have done:

<br>

- Working:
- [x] iPad-商城：首页&详情页&购买与支付([ #219](https://github.com/bstcine/cine-tasklist/issues/219))

<br>
<br>

## 2018-01-12:
- Have done:
- [ ] iPad-学习系统: Lesson播放页-Media对应的习题测试 ([#232](https://github.com/bstcine/cine-tasklist/issues/232))

<br>

- Working:
- [ ] iOS-购买与支付: 结算中心的收货地址信息管理 ([#241](https://github.com/bstcine/cine-tasklist/issues/241))
- [ ] iPad-APP: 测试问题反馈列表- V2.0.2 ([#230](https://github.com/bstcine/cine-tasklist/issues/230))

<br>
<br>

## 2018-01-16:
- Have done:
- [x] iOS-购买与支付: 结算中心的收货地址信息管理 ([#241](https://github.com/bstcine/cine-tasklist/issues/241))

<br>

- Working:
- [ ] iPad-APP: 测试问题反馈列表- V2.0.2 ([#230](https://github.com/bstcine/cine-tasklist/issues/230))

<br>
<br>

## 2018-01-19:
- Have done:

<br>

- Working:
- [ ] iPad-APP: 测试问题反馈列表- V2.0.2 ([#230](https://github.com/bstcine/cine-tasklist/issues/230))

<br>
<br>

## 2018-01-26:
- Have done:

<br>

- Working:
- [ ] iPhone-APP: 测试问题反馈列表- V2.0.2 ([#248](https://github.com/bstcine/cine-tasklist/issues/248))
- [ ] iPad-APP: 测试问题反馈列表- V2.0.2 ([#230](https://github.com/bstcine/cine-tasklist/issues/230))

<br>
<br>

  ## 2018-01-30:
- Working:
- [ ] iPhone-APP: 测试问题反馈列表- V2.0.2 ([#248](https://github.com/bstcine/cine-tasklist/issues/248))

<br>
<br>
