### ISSUE TITLE
2018-01: daily report - Leo

### ISSUE THREAD

**Issue by iott** [bstcine/cine-dailyreport#26]
## 2018-01-05:
- Have done:
H5-分享页：分享之后，新用户可领取优惠券(5%)，推荐人可获得积分奖励(10%) [(#105)](https://github.com/bstcine/cine-tasklist/issues/105)
  ```
  新用户领券&推荐人送积分逻辑
  ```
  H5-商城：课程详情页 - 测试问题反馈列表 - V2.0.2 [(#222)](https://github.com/bstcine/cine-tasklist/issues/222)
  ```
  结算中心bug修复
  ```
  H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情[(#36)](https://github.com/bstcine/cine-tasklist/issues/36)
  ```
  课程评价：添加状态和平台标识，修改逻辑
  ```
  API-购买与支付：购买前如果分享该课程，立刻享受95折 [(#160)](https://github.com/bstcine/cine-tasklist/issues/160)
  ```
   分享24小时内有效
   public和default的优惠：只针对视频课程类型
  ```

<br>

- Working:
- [ ] Database-调整: 把lesson表medias字段数据存放在lesson_media表 [(#214)](https://github.com/bstcine/cine-tasklist/issues/214)
<br>
<br>

## 2018-01-12:
- Have done:
  H5-商城：课程详情页 - 测试问题反馈列表 - V2.0.2 [(#222)](https://github.com/bstcine/cine-tasklist/issues/222)
  ```
  1. IOS课程概要和安卓课程概要有内容时候读取各自的内容，为空时候读取PC端的课程概要
  2. app-课程详情页（目前线上版本的App）：点击分享，不应该有相应的价格优惠
  3. IOS课程概要和安卓课程概要有内容时候读取各自的内容，为空时候读取PC端的课程概要
  4. 分享至微信端后没有享受优惠 Leo
  5.  优惠活动不支持排序
  ```
    API-数据统计：数据来源(sitecode) 收集 - 订单、分享、登入[(#229)](https://github.com/bstcine/cine-tasklist/issues/229)

<br>

- Working:
- [ ] Database-调整: 把lesson表medias字段数据存放在lesson_media表[(#214)](https://github.com/bstcine/cine-tasklist/issues/214)

<br>
<br>

## 2018-01-19:
- Have done:
  iPad-APP: 测试问题反馈列表- V2.0.2 [( #230)](https://github.com/bstcine/cine-tasklist/issues/230)          
  ```
  9-2.3.10 手动领取的新人优惠券不能自动匹配
  10-2.3.11 新人购买课程后，推荐人没有获得10%的积分奖励
  2.3.4 结算中心: 购买学习机时，通用优惠券也在“可使用优惠券”列表内，但不可用
  2.3.10 手动领取的新人优惠券不能自动匹配
  ```
  H5-商城：课程详情页 - 可扫二维码跟踪 [(#246)](https://github.com/bstcine/cine-tasklist/issues/246)
  API-购买与支付：订单需要包含收货地址等与发货信息 [(#242)](https://github.com/bstcine/cine-tasklist/issues/242)

<br>

- Working:
- [ ] Cine-WeChat：微信公众平台服务号-Template Message [(#235)](https://github.com/bstcine/cine-tasklist/issues/230)

<br>
<br>

## 2018-01-26:
- Have done:
  - PC-学习系统: 仅允许在商品详情中可以试听的课件在课程播放中展示并播放 [(251)](https://github.com/bstcine/cine-tasklist/issues/251)
  - Cine-WeChat：微信公众平台服务号-Template Message [(#235)](https://github.com/bstcine/cine-tasklist/issues/235)
  - H5-商城：课程详情页 - 可扫二维码跟踪 [(#246)](https://github.com/bstcine/cine-tasklist/issues/246)
  ```
  添加课程id追踪
  ```
  - 添加测试是否发布控制逻辑
  - 导入课程评论到官网
  - 官网发布够ios无法学习bug
  - 订单详情积分显示问题
  - 触发销售报表添加控制

<br>

## 2018-01-30:
- Have done:
api-购买与支付: 订单表中的使用积分point_discount最多保存2位小数 [(#261)](https://github.com/bstcine/cine-tasklist/issues/261)

<br>

- Working:
- [ ]  PC-后台管理：订单的地址信息展示 [(#260)](https://github.com/bstcine/cine-tasklist/issues/260)
