### ISSUE TITLE
2018-01: daily report - David

### ISSUE THREAD

**Issue by daweilv** [bstcine/cine-dailyreport#27]
## 2018-01-05

- Have done:
 - [x] H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情  ([#36](../../cine-tasklist/issues/36)) 

  ## 2018-01-09:
- Have done:
- [x] H5-商城：课程详情页 - 测试问题反馈列表 - V2.0.2([#222](../../cine-tasklist/issues/222))
- [x] 课程详情页添加header组件

<br>

- Working:
- [ ]  PC确认订单添加sitecode

<br>

## 2018-01-12
- Have Done:
- [x] PC确认订单添加sitecode
- [x] pc-H5: 词汇量测试-测试记录&词汇量排位图 ([#218](https://github.com/bstcine/cine-tasklist/issues/218))
<br>

- Working:
- [ ]  H5-购买与支付：PC端的结算中心页面需要与APP端一致([#238](https://github.com/bstcine/cine-tasklist/issues/238))

## 2018-01-16
- Have Done:
 - [x] pc-学习系统: 数据来源(sitecode) 收集-学习打卡分享 ([#245](https://github.com/bstcine/cine-tasklist/issues/245))
- Working:
 - 详情页、单词测试、结算中心bug fix

## 2018-01-19
 - Have Done:
 - [x] H5-购买与支付：PC端的结算中心页面需要与APP端一致 ([#238](https://github.com/bstcine/cine-tasklist/issues/238))
 - [x] 结算中心添加地址管理
 - [x] pc-H5: 词汇量测试-测试记录&词汇量排位图需求调整

## 2018-01-23
 - Have Done:
 - [x] 后台管理-手工开通权限页面添加有效期设置
 - [x] 支付宝支付开通 bug fix
 - [x] 老版结算中心自动使用优惠券
 - [x] 老版分享依然分享老详情页

## 2018-01-26
 - Have Done:
 - [x] 详情页样式调整
 - [x] 视频播放控件优化
 - [x] PC：使用新详情页， 但把“推荐得积分”&“领取95折新人优惠券”的功能 隐藏
 - [x] 对原来详情页的路径提供路径重定向
 - [x] 单词测试交互流程修改
 - [x] 现网mysql cpu 100%占用定位

 - Working:
 - [ ] H5首页
