### ISSUE TITLE
2018-02: daily report - Sprint Tasks - Aaron

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#31]
## 2018-01-29 ___ 02-02 :
- [x] iPhone-APP: 测试问题反馈列表- V2.0.2 ([#248](https://github.com/bstcine/cine-tasklist/issues/248))
- [ ] iPad：使用系统自带的Toolbar ([#262](https://github.com/bstcine/cine-tasklist/issues/262))

<br>
<br>

## 2018-02-05 ___ 02-09 :

<br>
<br>

## 2018-02-11 ___ 02-13 :

<br>
<br>

## 2018-02-22 ___ 02-24 :

<br>
<br>

## 2018-02-26 ___ 03-02 :
- [x] iOS-学习系统: 课程是有有效期的，用户不允许观看已过期的视频课程 ([#290](https://github.com/bstcine/cine-tasklist/issues/290))
- [x] iPad-商城：课程详情页-减少加载时间提升性能 ([#268](https://github.com/bstcine/cine-tasklist/issues/268))
- [x] iOS-商城：课程详情页不仅可以分享至朋友圈还可发送给朋友 ([#71](https://github.com/bstcine/cine-tasklist/issues/71))
- [ ] iOS-商城：商城首页-根据后台配置及相应规则, 偶尔会弹框提示 ([#292](https://github.com/bstcine/cine-tasklist/issues/292))
- [ ] iOS-Notification：系统级别的通知功能 ([#298](https://github.com/bstcine/cine-tasklist/issues/298))

<br>
<br>
