### ISSUE TITLE
2018-02: daily report - Sprint Tasks - Leo

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#34]
## 2018-01-29 ___ 02-02 :
Have Done:
- PC-后台管理：创建优惠活动及课程绑定对应的优惠活动操作界面优化 ([#259])(https://github.com/bstcine/cine-tasklist/issues/259)

Working:
- [x] PC-后台管理：订单的地址信息展示 ([#260])(https://github.com/bstcine/cine-tasklist/issues/260)
<br>
<br>

## 2018-02-05 ___ 02-09 :
Have Done:
- PC-后台管理：订单的地址信息展示 ([#260])(https://github.com/bstcine/cine-tasklist/issues/260)
```
  - 订单明细添加过滤需要发货的订单
  - 调整老版本的发货记录也显示在订单发货管理页
```
- 课程评论批量导入功能
- api-购买与支付: 订单表中有的订单记录没有Sitecode数据 ([#273])(https://github.com/bstcine/cine-tasklist/issues/273)

Working:
- [x] API-商城：课程详情页-增加新类型毅学小班([#267])(https://github.com/bstcine/cine-tasklist/issues/267) 

<br>
<br>

## 2018-02-11 ___ 02-13 :

<br>
<br>

## 2018-02-22 ___ 02-24 :
Hava Done:
PC-Tool: 销售日报- 添加“分享开通”的课程 [(#286)](https://github.com/bstcine/cine-tasklist/issues/286)
API-规范：admin route对应的命名 [(#282)](https://github.com/bstcine/cine-tasklist/issues/282)
<br>
<br>

## 2018-02-26 ___ 03-02 :
- Have Done:
- [x] API-购买与支付：微信支付- 支付成功后系统未开通相应的课程 [(#283)](https://github.com/bstcine/cine-tasklist/issues/283)
- [x] API-购买与支付：订单-48小时超时自动关闭，返回积分未到账 [(#300)](https://github.com/bstcine/cine-tasklist/issues/300)

- Working
- [ ] API-学习系统: 课程是有有效期的，用户不允许观看已过期的视频课程 [(#293)](https://github.com/bstcine/cine-tasklist/issues/300)
<br>
<br>
