### ISSUE TITLE
2018-02: daily report

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#35]
## 2018-02-05 ___ 02-09 :
- [x] H5-商城：官网首页 - http://www.bstcine.com/ ([#256](../../cine-tasklist/issues/256))
- [x] H5-商城：课程详情页-性能优化 ([#263](https://github.com/bstcine/cine-tasklist/issues/263))

<br>
<br>

## 2018-02-11 ___ 02-24 （春节） :

<br>
<br>

## 2018-02-26 ___ 03-02 :
- [x]  API-购买与支付：微信支付- 支付成功后系统未开通相应的课程 (#283)
- [x]  API-购买与支付：订单-48小时超时自动关闭，返回积分未到账 (#300)
- [ ] API-学习系统: 课程是有有效期的，用户不允许观看已过期的视频课程 [(#293)](https://github.com/bstcine/cine-tasklist/issues/300)
- [x] iOS-学习系统: 课程是有有效期的，用户不允许观看已过期的视频课程 ([#290](https://github.com/bstcine/cine-tasklist/issues/290))
- [x] iPad-商城：课程详情页-减少加载时间提升性能 ([#268](https://github.com/bstcine/cine-tasklist/issues/268))
- [x] iOS-商城：课程详情页不仅可以分享至朋友圈还可发送给朋友 ([#71](https://github.com/bstcine/cine-tasklist/issues/71))
- [ ] iOS-商城：商城首页-根据后台配置及相应规则, 偶尔会弹框提示 (#292)
- [ ] iOS-Notification：系统级别的通知功能 ([#298](https://github.com/bstcine/cine-tasklist/issues/298))
- [x] PC- 安全: 使用第三方云存储可随时为课程图片加水印 [#253](https://github.com/bstcine/cine-tasklist/issues/253)
- [x] PC-安全: 云存储OSS- 提供工具可对课程相关的Media资源进行迁移[#287](https://github.com/bstcine/cine-tasklist/issues/287)
- [ ] PC-后台管理: 课程管理-制作课件- 上传课件存放到OSS [#295](https://github.com/bstcine/cine-tasklist/issues/295)
 - [ ] H5-商城：课程详情页 - 详情内容与Header显示的是否登入状态不一致 ([#271](https://github.com/bstcine/cine-tasklist/issues/271))
<br>
<br>
