### ISSUE TITLE
2018-03: daily report - Sprint Tasks - Aaron

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#37]
## 2018-03-05 ___ 03-09 :
- [x] iOS-登录与注册: 香港手机号和美国手机号设置密码时都无法成功 ([#308](https://github.com/bstcine/cine-tasklist/issues/308))

<br>
<br>

## 2018-03-12 ___ 03-16 :
- [x] PC-Tool: 校验Lesson的课件数据是否都存在OSS ([#317](https://github.com/bstcine/cine-tasklist/issues/317))
- [x] PC-Tool: 阿里云存储OSS，可以下载某些Lesson的所有课件资源 ([#304](https://github.com/bstcine/cine-tasklist/issues/304))
- [x] iOS-商城：商城首页-根据后台配置及相应规则, 偶尔会弹框提示 ([#292](https://github.com/bstcine/cine-tasklist/issues/292))
- [x] iOS-Notification：系统级别的通知功能 ([#298](https://github.com/bstcine/cine-tasklist/issues/298))
- [x] iOS-商城：商城首页-根据API显示相应的Tab（如新增在线小班）([ #302](https://github.com/bstcine/cine-tasklist/issues/302))

<br>
<br>

## 2018-03-19 ___ 03-23 :
- [x] iOS-商城：预先提供-支持课程试听&Banner链接Tab等功能 ([327](https://github.com/bstcine/cine-tasklist/issues/327))

<br>
<br>

## 2018-03-26 ___ 03-30 👍 -

- [x] PC-Tool: 阿里云存储OSS，可以下载某些Lesson的所有课件资源 ([#304](https://github.com/bstcine/cine-tasklist/issues/304))
