### ISSUE TITLE
2018-03: daily report - Sprint Tasks - David

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#38]
## 2018-03-05 ___ 03-09 :
- [x] iOS-商城：商城首页-根据API显示相应的Tab（如新增在线小班） ([#302](https://github.com/bstcine/cine-tasklist/issues/302))
- [x] H5-购买与支付: 结算中心&提交订单&收银台&支付成功 功能整合 ([#274](https://github.com/bstcine/cine-tasklist/issues/274))
- [x] API-规范：购买与支付-使用V2.API  ([#279](https://github.com/bstcine/cine-tasklist/issues/279))

<br>
<br>

## 2018-03-12 ___ 03-16 :
- [x] API-学习系统: 针对某些学校的不同年级学生，提供某些课程不同章节的免费试听  ([#311](https://github.com/bstcine/cine-tasklist/issues/311))
```
Deadline: 2018-03-14
```
- [ ] H5-商城: 课程详情页- 调整课程试听功能及UI展现形式 ([#316](https://github.com/bstcine/cine-tasklist/issues/316))

<br>
<br>

## 2018-03-19 ___ 03-23 :
- [ ] H5-cine.pwa: build结果的目录结构，与源码src/client/entry的目录结构不一致  ([#321](https://github.com/bstcine/cine-tasklist/issues/321))

<br>
<br>

## 2018-03-26 ___ 03-30 👍
