### ISSUE TITLE
2018-03: daily report

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#39]
## 2018-03-05 ___ 03-09 :
- [x] PC-后台管理: 课程管理-制作课件- 上传课件存放到OSS [#295](https://github.com/bstcine/cine-tasklist/issues/295)  @Kim
```
目前进度：代码初步完成， 能上传课件了
```
- [x] H5-购买与支付: 结算中心&提交订单&收银台&支付成功 功能整合 ([#274](https://github.com/bstcine/cine-tasklist/issues/274))
- [x] API-规范：购买与支付-使用V2.API  ([#279](https://github.com/bstcine/cine-tasklist/issues/279))  @daweilv
- [x] API-规范：3端登录与注册 - 统一使用V2.API ([#280](https://github.com/bstcine/cine-tasklist/issues/280))
```
Deadline: 2018-03-12
```
- [ ] PC-消息管理：管理消息推送与设置（Notification&Message） ([#303](https://github.com/bstcine/cine-tasklist/issues/303))  @Leo
```
- 18-03-07: 确认新增加的表&后台管理页面
```

<br>
<br>

## 2018-03-12 ___ 03-16 :
- [ ] iOS-商城：商城首页-根据后台配置及相应规则, 偶尔会弹框提示 ([#292](https://github.com/bstcine/cine-tasklist/issues/292)) @Aaron
- [x] PC-安全: 云存储OSS- 课程相关的Media资源迁移  ([#289](https://github.com/bstcine/cine-tasklist/issues/289))  @Kim
- [x] API-学习系统: 针对某些学校的不同年级学生，提供某些课程不同章节的免费试听([#311](https://github.com/bstcine/cine-tasklist/issues/311))   @David

<br>
<br>

## 2018-03-19 ___ 03-23 :
- [ ] iOS-Notification：系统级别的通知功能
- [ ] iOS-商城：商城首页-根据API显示相应的Tab（如新增在线小班） ([#302](https://github.com/bstcine/cine-tasklist/issues/302)) @daweilv
```
- 18-03-06: 确认最终的Solution
目前进度：Solution已定
```
- [ ] Android-商城：商城首页-根据后台配置及相应规则, 偶尔会弹框提示 ([#322](https://github.com/bstcine/cine-tasklist/issues/322))
- [ ] PC-安全: 云存储OSS- 课件迁移遗留问题 ([#324](https://github.com/bstcine/cine-tasklist/issues/324))
- [ ] H5-商城: 课程详情页- 调整课程试听功能及UI展现形式  ([#316](https://github.com/bstcine/cine-tasklist/issues/316))
```
Step1: Phone版显示正常
```

<br>
<br>

## 2018-03-26 ___ 03-30 👍
