### ISSUE TITLE
2018-03: daily report - Sprint Tasks - Kim

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#40]
## 2018-03-05 ___ 03-09 :
- [x] PC-后台管理: 课程管理-制作课件- 上传课件存放到OSS [#295](https://github.com/bstcine/cine-tasklist/issues/295)
- [x]  PC-学习系统：Lesson播放页-播放的图片需要加上登入账号的水印  [#296](https://github.com/bstcine/cine-tasklist/issues/296)

<br>
<br>

## 2018-03-12 ___ 03-16 :
- [x]  PC-学习系统：Lesson播放页-播放的图片需要加上登入账号的水印  [#296](https://github.com/bstcine/cine-tasklist/issues/296)
- [x]  API-学习系统: Lesson播放页需要的API使用OSS的资源  [#297](https://github.com/bstcine/cine-tasklist/issues/297)
- [x] PC-学习系统：Email注册且未绑定手机的用户绑定手机 [#314](https://github.com/bstcine/cine-tasklist/issues/314)
<br>
<br>

## 2018-03-19 ___ 03-23 :
- [x] Android-Notification：系统级别的通知功能 [#323](https://github.com/bstcine/cine-tasklist/issues/323)
- [x] Android-商城：商城首页-根据后台配置及相应规则, 偶尔会弹框提示 [#322](https://github.com/bstcine/cine-tasklist/issues/322)
- [x] PC-学习系统: 学习首页-手机绑定异常 -紧急 [#329](https://github.com/bstcine/cine-tasklist/issues/329)

- [x] PC-安全: 云存储OSS- 课件迁移遗留问题 [#324](https://github.com/bstcine/cine-tasklist/issues/324)

- [x] Android-Demo: 检查与校验H5的功能与交互 [#332](https://github.com/bstcine/cine-tasklist/issues/332)

- [x] API-学习系统: Lesson播放页-树屋3-Lesson13的测验题的答案跟老师提供不一致 [#349](https://github.com/bstcine/cine-tasklist/issues/349)

- [x] Android-商城：商城首页-根据API显示相应的Tab（如新增在线小班）[#325](https://github.com/bstcine/cine-tasklist/issues/325)

- [x] PC-后台管理：课程管理-课程- 课件制作的试听不能删除及课程表同步试听失败 [#347](https://github.com/bstcine/cine-tasklist/issues/347)

<br>
<br>

## 2018-03-26 ___ 03-30 👍
