### ISSUE TITLE
2018-03: daily report - Sprint Tasks - Leo

### ISSUE THREAD

**Issue by iott** [bstcine/cine-dailyreport#41]
## 2018-03-05 ___ 03-09 :
- [x] API-规范：3端登录与注册 - 统一使用V2.API ([#280](https://github.com/bstcine/cine-tasklist/issues/280))
- [ ] PC-后台管理：管理消息推送与设置（Notification&Message） ([#303](https://github.com/bstcine/cine-tasklist/issues/303))
<br>
<br>

## 2018-03-12 ___ 03-16 :
- [x] PC-后台管理：管理消息推送与设置（Notification&Message）([#303](https://github.com/bstcine/cine-tasklist/issues/303))
- [ ] API-Code: 优化- 清除无用代码&代码编写规范 ([#301](https://github.com/bstcine/cine-tasklist/issues/301))

<br>
<br>

## 2018-03-19 ___ 03-23 :

<br>
<br>

## 2018-03-26 ___ 03-30:
