### ISSUE TITLE
2018-04: daily report -Tasks - Kim

### ISSUE THREAD

**Issue by kimliss** [bstcine/cine-dailyreport#42]
## 2018-04-09 ___ 04-13 :
- [x] PC-后台管理：课程管理-课程-制作课件-Lesson-Tag试听全选  [#356](https://github.com/bstcine/cine-tasklist/issues/356)

## 2018-04-23 - 04-27
- [x] H5-个人设置: 我的优惠券- 显示优惠券信息[#340](https://github.com/bstcine/cine-tasklist/issues/340)
- [x] PC-后台管理：管理消息推送与设置（Notification&Message）[#303](https://github.com/bstcine/cine-tasklist/issues/303)
- [x] H5-个人设置: 个人主页 & 积分 & 订单 & 优惠券 [#359](https://github.com/bstcine/cine-tasklist/issues/359)
