### ISSUE TITLE
2018-04: daily report -Tasks - Aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#43]
## 2018-04-09 ___ 04-13 :
- [ ] PC-Tool: 课件资源- 原图&音频&水印图 的校验 ([#353](https://github.com/bstcine/cine-tasklist/issues/353))
- [x] iOS-APP：测试问题反馈列表 - V2.3.1 ([#341](https://github.com/bstcine/cine-tasklist/issues/341))

## 2018-04-16 ___ 04-20 :
- [x] PC-Tool: 课件资源- 原图&音频&水印图 的校验 ([#353](https://github.com/bstcine/cine-tasklist/issues/353))
- [ ] PC-Tool: cine_course_download工具- 获取课件资源出错 ([#315](https://github.com/bstcine/cine-tasklist/issues/315))

## 2018-04-23 ___ 04-28 :
- [x] PC-Tool: cine_course_download工具- 获取课件资源出错 ([#315](https://github.com/bstcine/cine-tasklist/issues/315))
- [x] PC-Tool: cine_media_synthesizer工具- 合成课件资源为.mp4 ([#363](https://github.com/bstcine/cine-tasklist/issues/363))
- [x] PC-Tool: 课件合成视频(.mp4)工具- 遗留问题反馈 ([#364](https://github.com/bstcine/cine-tasklist/issues/364))
