### ISSUE TITLE
2018-04: daily report -Tasks - David

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#44]
## 2018-04-23 ___ 04-28 :
- [x] H5-测试: 语法和基础阅读能力测试 [#318](https://github.com/bstcine/cine-tasklist/issues/318)
- [x] H5-测试：核心语法测试- 测试问题反馈列表 [#361](https://github.com/bstcine/cine-tasklist/issues/361)
- [x] H5-商城：商城首页-根据API显示相应的Tab（如新增在线小班） [#380](https://github.com/bstcine/cine-tasklist/issues/380)
- [ ] pwa-项目：优化- 项目配置Webpack4 & 代码统一规范 [#379](https://github.com/bstcine/cine-tasklist/issues/379)
