### ISSUE TITLE
2018-05: daily report   - David

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#46]
## 2018-05-02 :
- [ ] ..

<br>

## 2018-05-07 ___ 05-11 :
- [x] H5-测试: 语法和基础阅读能力测试 [#318](https://github.com/bstcine/cine-tasklist/issues/318)
- [x] H5-测试：核心语法测试- 测试问题反馈列表 [#361](https://github.com/bstcine/cine-tasklist/issues/361)
- [x] H5-商城：商城首页-根据API显示相应的Tab（如新增在线小班） [#380](https://github.com/bstcine/cine-tasklist/issues/380)
- [ ] pwa-项目：优化- 项目配置Webpack4 & 代码统一规范 [#379](https://github.com/bstcine/cine-tasklist/issues/379)

<br>

## 2018-05-14 ___ 05-18 :
- [x] pwa-项目：优化- 项目配置Webpack4 & 代码统一规范 [#379](https://github.com/bstcine/cine-tasklist/issues/379)
- [ ] PC-后台管理: 私塾模块 - 老师学生管理&任务管理&任务分配 [#389](https://github.com/bstcine/cine-tasklist/issues/389)
<br>

## 2018-05-21 ___ 05-25 :
- [ ] PC-后台管理: 私塾模块 - 老师学生管理&任务管理&任务分配 [#389](https://github.com/bstcine/cine-tasklist/issues/389)

<br>

## 2018-05-28 :
- [ ] PC-后台管理: 私塾模块 - 老师学生管理&任务管理&任务分配 [#389](https://github.com/bstcine/cine-tasklist/issues/389)
