### ISSUE TITLE
2018-05: daily report - Aaron

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#47]
## 2018-05-02 :
- [ ] ..
- [x] PC-Tool: 课件合成视频(.mp4)工具- 遗留问题反馈 ([#364](https://github.com/bstcine/cine-tasklist/issues/364))
- [x] PC-Tool: cine_media_synthesizer工具- 合成课件资源为.mp4 ([#363](https://github.com/bstcine/cine-tasklist/issues/363))
<br>

## 2018-05-07 ___ 05-11 :
- [ ] ..
- [x] PC-Tool: cine_media_synthesizer工具- 合成课件资源为.mp4 ([#363](https://github.com/bstcine/cine-tasklist/issues/363))
- [ ] H5-个人设置: 我的订单- 显示订单信息 ([#369](https://github.com/bstcine/cine-tasklist/issues/369))
<br>

## 2018-05-14 ___ 05-18 :
- [ ] ..
- [x] PC-Tool: cine_media_synthesizer工具- 合成课件资源为.mp4 ([#363](https://github.com/bstcine/cine-tasklist/issues/363))
- [ ] H5-个人设置: 我的订单- 显示订单信息 ([#369](https://github.com/bstcine/cine-tasklist/issues/369))
<br>

## 2018-05-21 ___ 05-25 :
- [ ] ..
- [x] PC-Tool: cine_media_synthesizer工具- 合成课件资源为.mp4 ([#363](https://github.com/bstcine/cine-tasklist/issues/363))
- [ ] H5-个人设置: 我的订单- 显示订单信息 ([#369](https://github.com/bstcine/cine-tasklist/issues/369))
- [x] PC-Tool: cine_course_download - 下载没有二维码的课件图片 ([#390](https://github.com/bstcine/cine-tasklist/issues/390))
<br>

## 2018-05-28 :
- [ ] ..
- [x] PC-Tool: cine_course_download - 下载没有二维码的课件图片 ([#390](https://github.com/bstcine/cine-tasklist/issues/390))
- redux的学习与应用
