### ISSUE TITLE
2018-05: daily report - Kim

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#48]
## 2018-05-02 :
- [ ] ..

<br>

## 2018-05-07 ___ 05-11 :
- [x] API-学习系统: 跟踪记录用户学习时所使用的设备（sitecode） [#366](https://github.com/bstcine/cine-tasklist/issues/366)
- [x] H5-个人设置: 个人主页 & 积分 & 优惠券等 [#359](https://github.com/bstcine/cine-tasklist/issues/359)

<br>

## 2018-05-14 ___ 05-18 :
- [x] H5-老师中心：可查看学生的语法测试列表&词汇测试列表 [#381](https://github.com/bstcine/cine-tasklist/issues/381)

<br>

## 2018-05-21 ___ 05-25 :
- [x] H5-优惠: 对购买过永久有效期课程的用户送优惠券提醒 - （临时性代码） [#385](https://github.com/bstcine/cine-tasklist/issues/385)
- [x] API-购买与支付: 订单-新购买的订单有效期为2年 - （临时性代码） [#392](https://github.com/bstcine/cine-tasklist/issues/392)

<br>

## 2018-05-28 :
- [x] API-个人设置: 优惠券可转让给其它账号 [#401](https://github.com/bstcine/cine-tasklist/issues/410)
