### ISSUE TITLE
2018-06: daily report - Aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#49]
## 2018-06-04 ___ 06-08 :
- [x] iOS-个人设置: 优惠券页面- 数量大于10，超出整十部分的优惠券没有显示出来 ([#403](https://github.com/bstcine/cine-tasklist/issues/403))
- [x] 优惠券模块

<br>

## 2018-06-11 ___ 06-15 :
- [x] PC-后台管理: 私塾任务基础数据- 核心词汇top10000 ([#394](https://github.com/bstcine/cine-tasklist/issues/394))  
```
Status: 音标与汉语翻译基本完成（音标剩余14个，包含翻译剩余2个）
        发音部分尚未处理
```

- [x] 优惠券模块

<br>

## 2018-06-18 ___ 06-22 :

- [x] H5-学习系统: 私塾词汇任务- 简易式的词汇学习 ([#397](https://github.com/bstcine/cine-tasklist/issues/397))
```
Status:fixed
```

- [x] API-学习系统: Top10000的词汇学习 & 课件的词汇学习 ([#412](https://github.com/bstcine/cine-tasklist/issues/412))
```
Status: Top10000词汇已提供接口获取，
        课件的词汇学习尚未完成
```

- [x] H5-学习系统: 任务历史页- 查看以前所有任务记录(视频课件&词汇&习题)  ([#391](https://github.com/bstcine/cine-tasklist/issues/391))
```
Status: 界面已完成
        api数据已接入
        筛选弹窗已弹出，（类型选择一栏中，字体和大小尚未完成）
        筛选方法尚未完成
```

- [x] 任务基础数据 - 词汇发音抓取 & 资源保存到OSS ([#411](https://github.com/bstcine/cine-tasklist/issues/411))
```
Status:发音抓取完毕
```

<br>

## 2018-06-25 ___ :
- [ ] ..
- [x] API-学习系统: Top10000的词汇学习 & 课件的词汇学习 ([#412](https://github.com/bstcine/cine-tasklist/issues/412))
```
Status: ？
```

- [x] H5-学习系统: 任务历史页- 查看以前所有任务记录(视频课件&词汇&习题)  ([#391](https://github.com/bstcine/cine-tasklist/issues/391))
```
Status: 
```

- [x] H5-学习系统: 私塾词汇作业- 学完后词汇测试  ([#398](https://github.com/bstcine/cine-tasklist/issues/398))
```
Status: ?
```

- [x] API-学习系统: Top10000的词汇学习 & 课件的词汇学习 ([#412](https://github.com/bstcine/cine-tasklist/issues/412))
```
Status: Top10000词汇已提供接口获取，
        课件的词汇学习尚未完成
```

- [x] H5-学习系统: 任务历史页- 查看以前所有任务记录(视频课件&词汇&习题)  ([#391](https://github.com/bstcine/cine-tasklist/issues/391))
```
Status: 界面已完成
        api数据已接入
        筛选弹窗已弹出，（类型选择一栏中，字体和大小尚未完成）
        筛选方法尚未完成
```
<br>

**Comment by joelin109** [comment]
#52
