### ISSUE TITLE
2017-10: daily report - Aaron

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#5]
### 2017-10-10
- Have done:
  [#46 iOS-商城： 增加不登录购买产品功能](https://github.com/bstcine/cine-tasklist/issues/46)
  [help: iOS-部署与发布](https://github.com/bstcine/help/wiki/iOS-部署与发布)

<br>

- Working:

<br>

### 2017-10-13
- Have done:
-  [#14 iOS-购买与支付: 添加内购功能](https://github.com/bstcine/cine-tasklist/issues/14)
-  [#62 iOS-下载：播放已下载的lesson出现闪退（bug已解决，@李党坤补充解决方案）](https://github.com/bstcine/cine-tasklist/issues/62)
 <br>

- Working:

<br>

### 2017-10-17
- Have done:
-  [#63 iOS-学习系统：手机处于静音模式时，播放课程也能够正常听见音频](https://github.com/bstcine/cine-tasklist/issues/63)
-  [#59 iOS-下载：删除已下载的lesson出现闪退](https://github.com/bstcine/cine-tasklist/issues/59)
<br>

- Working:

<br>

### 2017-10-20
- Have done:

<br>

- Working:

<br>

### 2017-10-24
- Have done:

<br>

- Working:
(https://github.com/bstcine/cine-tasklist/issues/65)

<br>

### 2017-10-27
- Have done:
- [x]  [#81 iOS-商城：用户购买课程使用的账号是api_ios_buy,无法开通课程](https://github.com/bstcine/cine-tasklist/issues/81)
- [x]  [#65 iOS-Code规范：迁移到项目的V2框架 - Extension&Vendor模块]
<br>

- Working:
- [ ] [#66 iOS-Code规范：迁移到项目的V2框架 - Util 模块](https://github.com/bstcine/cine-tasklist/issues/66)

<br>

### 2017-10-31
- Have done:

<br>

- Working:
- [ ] iOS-Code规范：把现有的功能迁移到V2 （[#84](https://github.com/bstcine/cine-tasklist/issues/84))
- [ ] [#66 iOS-Code规范：迁移到项目的V2框架 - Util 模块](https://github.com/bstcine/cine-tasklist/issues/66)

**Comment by joelin109** [comment]
### 2017-11-07
- Have done:


- Working:

<br>

### 2017-11-10
- Have done:


- Working:

<br>

### 2017-11-14
- Have done:


- Working:

<br>

### 2017-11-17
- Have done:


- Working:

<br>
