### ISSUE TITLE
2018-06: daily report - David

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#50]
## 2018-06-11 ～ 2018-06-15:
- [x] PC-后台管理: 私塾模块 - 老师学生管理&任务管理&任务分配 ([#389](https://github.com/bstcine/cine-tasklist/issues/389)) 
```
Status: 完成
```
- [ ] PWA-项目：配置部署优化 [#405](https://github.com/bstcine/cine-tasklist/issues/405)
- [ ] PWA-项目：学习首页 & 用户中心 & 导师批改 模块使用统一的GHeader [#408](https://github.com/bstcine/cine-tasklist/issues/408)
```
Status: 一级GHeader页面完成（含动态active）
```
<br>
<br>

## 2018-06-19 ～ 2018-06-22:
- [x] H5-学习系统: 学习首页-私塾模块：显示 “视频课件”&“习题”&“词汇”作业类型  ([#406](https://github.com/bstcine/cine-tasklist/issues/406))
```
Status: iPad 适配 UI完成，剩余工作：手机端交互
```
- [x] API-导师批改：导师所属学生的本周作业列表 [#418](https://github.com/bstcine/cine-tasklist/issues/418)

<br>
<br>

## 2018-06-25 ～ 2018-06-29:
- [ ] H5-学习系统: 私塾模块 - 测试反馈列表 [#416](https://github.com/bstcine/cine-tasklist/issues/416)

**Comment by joelin109** [comment]
#52
