### ISSUE TITLE
2018-06: daily report - Kim

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#51]
## 2018-06-11 ～ 2018-06-15:
- [x] PC-后台管理: 私塾任务基础数据- lesson_quiz历史数据需导入question表 （[#407](https://github.com/bstcine/cine-tasklist/issues/407)）  
```
Status: ?
```
- [x] PC-后台管理: 私塾任务基础数据- 习题基础数据 （[#400](https://github.com/bstcine/cine-tasklist/issues/400)）  
```
Status: ?
```
- [ ] API-学习系统: Lesson播放页-记录用户在每个课程上的实际学习时间 [#386](https://github.com/bstcine/cine-tasklist/issues/386)

<br>

## 2018-06-19 ___ 06-22 :
- [x] API-学习系统: 习题测试页面需要的数据  ([#409](https://github.com/bstcine/cine-tasklist/issues/409))
- [x] H5-学习系统: 私塾习题任务- 习题测试（包含客观题和主观题）([#399](https://github.com/bstcine/cine-tasklist/issues/399))

<br>

## 2018-06-25 ～ 2018-06-29:
- [ ] H5-学习系统: 习题测试、练习、批改 - 测试反馈列表 [#417](https://github.com/bstcine/cine-tasklist/issues/417)
- [x] H5-导师批改: 可以看到私塾学生的本周作业情况 ([#396](https://github.com/bstcine/cine-tasklist/issues/396))

**Comment by joelin109** [comment]
#52
