### ISSUE TITLE
2018-06: daily report

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#52]
## 2018-06-11 ___ 06-15 :
- [x] PC-后台管理: 私塾任务基础数据- lesson_quiz历史数据需导入question表 （[#407](https://github.com/bstcine/cine-tasklist/issues/407)）  @Kim
```
Status: Done
```
- [ ] PC-后台管理: 私塾任务基础数据- 习题基础数据 （[#400](https://github.com/bstcine/cine-tasklist/issues/400)）  @Kim
```
Status: ?

Problem：
        数据重复的问题需要一个Solution
```
- [x] PC-后台管理: 私塾任务基础数据- 核心词汇top10000 ([#394](https://github.com/bstcine/cine-tasklist/issues/394))  @AaronLiDangkun
```
Status: ?
```
- [x] PC-后台管理: 私塾模块 - 老师学生管理&任务管理&任务分配 ([#389](https://github.com/bstcine/cine-tasklist/issues/389)) 
```
Status: ?
```
- [ ] H5-学习系统: 学习首页-私塾模块：显示 “视频课件”&“习题”&“词汇”作业类型  ([#406](https://github.com/bstcine/cine-tasklist/issues/406))
```
Status: Working
```
- [ ] H5-学习系统: 私塾词汇任务- 简易式的词汇学习  ([#397](https://github.com/bstcine/cine-tasklist/issues/397))   @AaronLiDangkun 
```
Status: ?
Deadline：2018-06-21
```
 

<br>
<br>

## 2018-06-19 ___ 06-22 :
- [x] H5-学习系统: 学习首页-私塾模块：显示 “视频课件”&“习题”&“词汇”作业类型  ([#406](https://github.com/bstcine/cine-tasklist/issues/406))
```
Demo Deadline：2018-06-21  10AM
```
- [x] H5-学习系统: 私塾习题任务- 习题测试（包含客观题和主观题）([#399](https://github.com/bstcine/cine-tasklist/issues/399))
```
Deadline：2018-06-22  3 PM
```
- [ ] H5-学习系统: 私塾词汇作业- 学完后词汇测试  ([#398](https://github.com/bstcine/cine-tasklist/issues/398))
- [x] H5-学习系统: 任务历史页- 查看以前所有任务记录(视频课件&词汇&习题)  ([#391](https://github.com/bstcine/cine-tasklist/issues/391))

<br>
<br>

## 2018-06-25 ___ 06-29 :
- [x] H5-学习系统: 私塾词汇作业- 学完后词汇测试  ([#398](https://github.com/bstcine/cine-tasklist/issues/398))
- [ ] H5-导师批改: 可以看到私塾学生的本周作业情况 ([#396](https://github.com/bstcine/cine-tasklist/issues/396)) @Kim

<br>
<br>
