### ISSUE TITLE
 2018-07: daily report - Aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#54]
## 2018-07-02 ___ 07-06 :
- [x] ...
- [x] H5-学习系统: 私塾模块 - 测试反馈列表 ([#416](https://github.com/bstcine/cine-tasklist/issues/416))
```
Status: 3.1. api 已支持获取错误词汇，UI显示待确定
        3.2. 已完成
        3.3-2.2. 已完成
        3.4-3.5. 已完成 (已补足了没有发音的模块)
        4.1. 已完成
        4.2. 已完成
        4.3. 已完成
        4.4. 已完成
        4.5. 已完成
        4.6. 已完成
        4.7. 已完成
```
<br>

## 2018-07-09 ___ 07-13 :
- [x] ...
- [x] H5-学习系统: 私塾模块 - 测试反馈列表 ([#416](https://github.com/bstcine/cine-tasklist/issues/416))
- [x] iPad-商城：课程详情页-减少加载时间提升性能 ([#268](https://github.com/bstcine/cine-tasklist/issues/268))
```
Status:
    1.将加载过程中获取的资源文件，缓存到沙盒中    -已完成
       再次获取资源文件时，不再读取网络数据       -已完成
    2.将加载过程中产生的api数据缓存到沙盒中       -已完成
        在没有网络的状况下，使用缓存的api数据     -未完成
    3.时时更新本地资源文件，清理过期文件          -未完成
```
- [x] PC-OSS: 非课件的Media资源迁移 ([#326](https://github.com/bstcine/cine-tasklist/issues/326))
```
Status：转下周
```
- [x] PC-OSS: 课程封面&用户头像的资源迁移到OSS ([#377](https://github.com/bstcine/cine-tasklist/issues/377))
<br>

## 2018-07-16 ___ 07-20 :
[ ] ...
- [x] iPad-商城：课程详情页-减少加载时间提升性能 ([#268](https://github.com/bstcine/cine-tasklist/issues/268))
```
Status:
    2.在没有网络的状况下，使用缓存的api数据     -已完成
    3.时时更新本地资源文件，清理过期文件          -已完成
```
- [x] PC-OSS: 非课件的Media资源迁移 ([#326](https://github.com/bstcine/cine-tasklist/issues/326))
- [X] PC-OSS: 课程封面&用户头像的资源迁移到OSS ([#377](https://github.com/bstcine/cine-tasklist/issues/377))
<br>

## 2018-07-23 ___ 07-27 :
[ ] ...
- [x] H5-营销活动: 让用户通过扫码或者点击链接, 自动领用优惠券功能 ([#429](https://github.com/bstcine/cine-tasklist/issues/429))
- [x] 更新数据库前2000个单词（top1234）
- [x] H5-学习系统: 词汇学习-卡片式 ([#426](https://github.com/bstcine/cine-tasklist/issues/426))
<br>

## 2018-07-30 ___  08-03:
[ ] ...
- [x] H5-学习系统: 词汇学习-卡片式 ([#426](https://github.com/bstcine/cine-tasklist/issues/426))
<br>
<br>
