### ISSUE TITLE
2018-08: daily report - Aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#55]
## 2018-08-06 ___ 08-10 :
- [x] ...
- [x] H5-学习系统: 词汇学习-卡片式 ([#426](https://github.com/bstcine/cine-tasklist/issues/426))
<br>

## 2018-08-13 ___ 08-17 :
- [x] ...
- [x] H5-学习系统: 词汇学习-卡片式 ([#426](https://github.com/bstcine/cine-tasklist/issues/426))
- [x] H5-学习系统: 词汇学习- 词汇起点评估建议 ([#443](https://github.com/bstcine/cine-tasklist/issues/443))
<br>

## 2018-08-20 ___ 08-24: 
- [x] ...
- [x] H5-学习系统: 词汇学习- 词汇起点评估建议 ([#443](https://github.com/bstcine/cine-tasklist/issues/443))
- [x] H5-学习系统: 词汇课程学习- top10000分3门课程（入口在学习首页） ([#449](https://github.com/bstcine/cine-tasklist/issues/449))
- [x] H5-学习系统: 词汇模块 - 测试反馈列表 ([#448](https://github.com/bstcine/cine-tasklist/issues/448))
```
1.卡片式词汇学习，随机播放功能
  status: done
```
<br>

## 2018-08-27 ___ 08-31 :
- [x] ...
- [x] H5-学习系统: 词汇模块 - 测试反馈列表 ([#448](https://github.com/bstcine/cine-tasklist/issues/448))
- [x] iPad-学习系统：添加私塾模块 ([#440](https://github.com/bstcine/cine-tasklist/issues/440))
```
1. iPhone 切入学习任务界面 - working

2.iPad切入学习首页 - prepare
status: 转2018-09
```
<br>
