### ISSUE TITLE
2018-09: daily report - Aaron

### ISSUE THREAD

**Issue by AaronLiDangkun** [bstcine/cine-dailyreport#56]
## 2018-09-03 ___ 09-07 :
- [x] H5-学习系统: 词汇模块 - 测试反馈列表 ([#448](https://github.com/bstcine/cine-tasklist/issues/448))
- [x] H5-学习系统：词汇学习模块- 重新调整UI & 整理中文翻译等 ([#455](https://github.com/bstcine/cine-tasklist/issues/455))
- [x] iOS-iPhone：V-2.4.0（包含私塾模块） ([#454](https://github.com/bstcine/cine-tasklist/issues/454))
- [ ] iPad-学习系统：添加私塾模块 ([#440](https://github.com/bstcine/cine-tasklist/issues/440))
```
1. iPhone 切入学习任务界面 - working

2.iPad切入学习首页 - prepare
```
<br>

## 2018-09-10 ___ 09-14 :
- [x] ...
- [ ] H5-学习系统：词汇学习模块- 重新调整UI & 整理中文翻译等 ([#455](https://github.com/bstcine/cine-tasklist/issues/455))
- [ ] Realese-v2.4: 发布前测试的问题反馈列表 ([#456](https://github.com/bstcine/cine-tasklist/issues/456))
<br>

## 2018-09-17 ___ 09-21: 
- [x] ...
<br>
- [ ] Realese-v2.4.1: 测试发现新问题的反馈列表 ([#457](https://github.com/bstcine/cine-tasklist/issues/457))
- [ ] iOS-iPhone：V-2.4.1（包含私塾模块） ([#454](https://github.com/bstcine/cine-tasklist/issues/454))

## 2018-09-24 ___ 09-28 :
- [x] ...
<br>
