### ISSUE TITLE
2017-10: daily report - Kim

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#6]
### 2017-10-10
- Have done:
[#45 修复 v1.0.6 版本 BUG](https://github.com/bstcine/cine-tasklist/issues/45)

<br>

- Working:
- [x] [#48 安卓pad：打卡、购买课程支付方式和分享等功能与web端一致](https://github.com/bstcine/cine-tasklist/issues/48)

<br>

### 2017-10-13
- Have done:
[#55 暨阳中学学习账号添加及开通对应课程](https://github.com/bstcine/cine-tasklist/issues/55)
[#48 安卓pad：打卡、购买课程支付方式和分享等功能与web端一致](https://github.com/bstcine/cine-tasklist/issues/48)

<br>

- Working:

<br>

### 2017-10-17
- Have done:

<br>

- Working:
- [x]  [#61 安卓-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新](https://github.com/bstcine/cine-tasklist/issues/61)

<br>

### 2017-10-20
- Have done:

<br>

- Working:
- [x]  [#61 安卓-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新](https://github.com/bstcine/cine-tasklist/issues/61)

<br>

### 2017-10-24
- Have done:
- [x]  [#61 安卓-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新](https://github.com/bstcine/cine-tasklist/issues/61)
<br>

- Working:
- [x]  [#94 安卓-学习系统：离线课程也需要保存学习状态](https://github.com/bstcine/cine-tasklist/issues/94)

<br>

### 2017-10-27
- Have done:
- [x]  [#94 安卓-学习系统：离线课程也需要保存学习状态](https://github.com/bstcine/cine-tasklist/issues/94)
<br>

- Working:
- [x]  [#94 Android-Code调整：移动端使用统一的Model定义，然后代码check in `Gitee`](https://github.com/bstcine/cine-tasklist/issues/90)

<br>

### 2017-10-31
- Have done:
- [x]  [#94 Android-Code调整：移动端使用统一的Model定义，然后代码check in `Gitee`](https://github.com/bstcine/cine-tasklist/issues/90)
<br>

- Working:
- [x]  [#49 安卓-下载：已下载课程目录显示方式](https://github.com/bstcine/cine-tasklist/issues/49)
