### ISSUE TITLE
2017-10: daily report - Liming

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#7]
### 2017-10-10
- Have done:
 [#46 IOS-商城：搜索已经购买的课程仍然有立即购买的按钮](https://github.com/bstcine/cine-tasklist/issues/44)
[#37 iOS-学习系统：播放时竖屏切换横屏时，左右切换箭头（上一章下一章）变小（被缩放)](https://github.com/bstcine/cine-tasklist/issues/37)
 [#35 iOS-Code调整：把所有的Model都放在统一的Model目录中](https://github.com/bstcine/cine-tasklist/issues/35)
 [#19  iOS-个人设置： 一键分享APP](https://github.com/bstcine/cine-tasklist/issues/19)

- Working:

- [ ]  [#34 iOS-学习系统：播放界面课程标题]
       (https://github.com/bstcine/cine-tasklist/issues/34)
- [ ]  [#15 iOS-学习系统-课程播放界面控制操作]
      (https://github.com/bstcine/cine-tasklist/issues/15)
<br>

### 2017-10-13
- Have done:
 [#15 iOS-学习系统-课程播放界面控制操作]
      (https://github.com/bstcine/cine-tasklist/issues/15)
  [#35 iOS-Code调整：把所有的Model都放在统一的Model目录中]
       (https://github.com/bstcine/cine-tasklist/issues/35)
- Working:
- [x ]  [#57 iOS-Code规范：迁移到项目的V2框架 - Model模块整理]
       (https://github.com/bstcine/cine-tasklist/issues/57)

- [ ]  [#34 iOS-学习系统：播放界面课程标题]
       (https://github.com/bstcine/cine-tasklist/issues/34)

<br>

### 2017-10-17
- Have done:
 [#57 iOS-Code规范：迁移到项目的V2框架 - Model模块整理]
       (https://github.com/bstcine/cine-tasklist/issues/57)
<br>

       
- Working:
- [ ] [#78 iOS-Code规范：迁移到项目的V2框架 : 字体&颜色部分](https://github.com/bstcine/cine-tasklist/issues/78)
<br>

### 2017-10-20
- Have done:

<br>

- Working:
- [ ]  [...](../../cine-tasklist/issues/?)

<br>

### 2017-10-24
- Have done:

<br>

- Working:
- [ ]  [...](../../cine-tasklist/issues/?)

<br>

### 2017-10-27
- Have done:

<br>

- Working:
- [ ]  [...](../../cine-tasklist/issues/?)

<br>

### 2017-10-31
- Have done:

<br>

- Working:
- [ ]  [...](../../cine-tasklist/issues/?)
