### ISSUE TITLE
2017-10: daily report - Leo

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#8]
### 2017-10-10
- Have done:
 追踪管理员查看课程详情页
修改app分享逻辑 [#33](https://github.com/bstcine/cine-tasklist/issues/33)
9/26-10/8 购买并成功分享报表
<br>

- Working:
-  [x]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
```
2.1 内容 部分api
```

<br>

### 2017-10-13
- Working:
-  [x]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
```
  2.1 内容部分api
```
<br>

### 2017-10-17
- Have done:
    [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
   2.1课程 部分api
 ```

- Working:
- [ ] [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
  2.2 订单 部分api
 ```
<br>

### 2017-10-20
- Have done:
  [iOS-商城：用户购买课程使用的账号是api_ios_buy,无法开通课程 #81](https://github.com/bstcine/cine-tasklist/issues/81)
```
增加api app审核记录
```
<br>

- Working:
- [ ]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)

<br>

### 2017-10-24
- Have done:
    [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
   2.2订单&支付 部分api
 ```

- Working:
- [ ]  [PC-后台-课程管理：课件批量录入 #21](https://github.com/bstcine/cine-tasklist/issues/21)

<br>

### 2017-10-27
- Working:
- [ ]  [PC-后台-课程管理：课件批量录入 #21](https://github.com/bstcine/cine-tasklist/issues/21)

<br>

### 2017-10-31
- Have done:
- [x]  [PC-后台-课程管理：课件批量录入 #21](https://github.com/bstcine/cine-tasklist/issues/21)

- Working:
    [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
   2.4个人中心 部分api
 ```
<br>

### 2017-11-3
- Have done:
- [x]   [API-iOS: iOS发布版本前，积分计算规则-先避免输入超过可用积分变为0的情况 #102](https://github.com/bstcine/cine-tasklist/issues/102)
- [x]  [api-Code规范：提供V2版本的api #42](https://github.com/bstcine/cine-tasklist/issues/42)
 ```
   2.4个人中心 部分api
 ```
- Working:
    [pc-后台管理: 词汇量测试设计 - 文档数据导入 #115](https://github.com/bstcine/cine-tasklist/issues/115)

<br>
