### ISSUE TITLE
2017-10: daily report - Zohar

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-dailyreport#9]
### 2017-10-10
- Have done:
  项目环境基本配置；
  编写示范 Demo；

<br>

- Working:
- [x]  [iOS-Code规范：提供iOS项目的框架 #38](https://github.com/bstcine/cine-tasklist/issues/38) 

<br>

### 2017-10-13
- Have done:

   [iOS-Code规范：提供iOS项目的框架 #38](https://github.com/bstcine/cine-tasklist/issues/38) 网络层搭建的完善;
   为范例添加说明注释；

<br>

- Working:
- [x] [iOS-Code规范：迁移到项目的V2框架 - UI界面的列表清单 #68 ](https://github.com/bstcine/cine-tasklist/issues/68);
- [x] [iOS-下载：已下载的课程内容更新 #60 ](https://github.com/bstcine/cine-tasklist/issues/60);

<br>

### 2017-10-17
- Have done:

   [iOS-Code规范：迁移到项目的V2框架 - UI界面的列表清单 #68 ](https://github.com/bstcine/cine-tasklist/issues/68);

<br>

- Working:

- [x]  [iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60 ](https://github.com/bstcine/cine-tasklist/issues/60);
- [ ]  [iOS-Code规范：为Cine.iOS framework 提供合适的 Bundle 资源文件解决方案 #79](https://github.com/bstcine/cine-tasklist/issues/79)；

<br>

### 2017-10-20
- Have done:
 [iOS-Code规范：迁移到项目的V2框架 - UI界面的列表清单 #68 ](https://github.com/bstcine/cine-tasklist/issues/68);
<br>

- Working:
- [x]  [iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60 ](https://github.com/bstcine/cine-tasklist/issues/60);

<br>

### 2017-10-24
- Have done:

<br>

- Working:
- [x]  [iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60 ](https://github.com/bstcine/cine-tasklist/issues/60);

<br>

### 2017-10-27
- Have done:

<br>

- Working:
- [x]  [iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60 ](https://github.com/bstcine/cine-tasklist/issues/60);

<br>

### 2017-10-31
- Have done:
[iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新 #60](https://github.com/bstcine/cine-tasklist/issues/60)
<br>

- Working:
- [x]  [iOS-项目架构:   提供 Cine.iOS 工程项目的创建文档Doc #111](https://github.com/bstcine/cine-tasklist/issues/111)
- [x]  [iOS-项目架构：提供 Carthage 替换 Cocoapods 的方案，并编写文档 #112](https://github.com/bstcine/cine-tasklist/issues/112)

**Comment by YinZhenJob** [comment]
- Have done:
1. 项目环境基本配置；
2. 编写示范 Demo；

- Working:
1. 网络层架构搭建；
2. 定义网络异常CError；
3. 模型定义商议；

**Comment by joelin109** [comment]
没有正在做的task，不用加到working列表中
